---
version: "2"
plugins:
  duplication:
    enabled: true
    exclude_paths:
    - spec/
    - lib/elftools/constants.rb
checks:
  method-lines:
    enabled: false
  method-count:
    enabled: false
  method-complexity:
    config:
      threshold: 10
exclude_patterns:
- "spec/"
