AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Naming/ClassAndModuleCamelCase:
  Exclude:
    - lib/elftools/structs.rb
    - lib/elftools/constants.rb

Naming/ConstantName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
