AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Enabled: true
  Max: 120

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/ModuleLength:
  Exclude:
    - lib/elftools/constants.rb

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Exclude:
    - lib/elftools/structs.rb
    - lib/elftools/constants.rb

Naming/ConstantName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
