# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of AMDGPU.
      module AMDGPU
        R_AMDGPU_NONE          = 0 # :nodoc:
        R_AMDGPU_ABS32_LO      = 1 # :nodoc:
        R_AMDGPU_ABS32_HI      = 2 # :nodoc:
        R_AMDGPU_ABS64         = 3 # :nodoc:
        R_AMDGPU_REL32         = 4 # :nodoc:
        R_AMDGPU_REL64         = 5 # :nodoc:
        R_AMDGPU_ABS32         = 6 # :nodoc:
        R_AMDGPU_GOTPCREL      = 7 # :nodoc:
        R_AMDGPU_GOTPCREL32_LO = 8 # :nodoc:
        R_AMDGPU_GOTPCREL32_HI = 9 # :nodoc:
        R_AMDGPU_REL32_LO      = 10 # :nodoc:
        R_AMDGPU_REL32_HI      = 11 # :nodoc:
        R_AMDGPU_RELATIVE64    = 13 # :nodoc:
        R_AMDGPU_REL16         = 16 # :nodoc:
      end
    end
  end
end
