# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of AVR.
      module AVR
        R_AVR_NONE           = 0 # :nodoc:
        R_AVR_32             = 1 # :nodoc:
        R_AVR_7_PCREL        = 2 # :nodoc:
        R_AVR_13_PCREL       = 3 # :nodoc:
        R_AVR_16             = 4 # :nodoc:
        R_AVR_16_PM          = 5 # :nodoc:
        R_AVR_LO8_LDI        = 6 # :nodoc:
        R_AVR_HI8_LDI        = 7 # :nodoc:
        R_AVR_HH8_LDI        = 8 # :nodoc:
        R_AVR_LO8_LDI_NEG    = 9 # :nodoc:
        R_AVR_HI8_LDI_NEG    = 10 # :nodoc:
        R_AVR_HH8_LDI_NEG    = 11 # :nodoc:
        R_AVR_LO8_LDI_PM     = 12 # :nodoc:
        R_AVR_HI8_LDI_PM     = 13 # :nodoc:
        R_AVR_HH8_LDI_PM     = 14 # :nodoc:
        R_AVR_LO8_LDI_PM_NEG = 15 # :nodoc:
        R_AVR_HI8_LDI_PM_NEG = 16 # :nodoc:
        R_AVR_HH8_LDI_PM_NEG = 17 # :nodoc:
        R_AVR_CALL           = 18 # :nodoc:
        R_AVR_LDI            = 19 # :nodoc:
        R_AVR_6              = 20 # :nodoc:
        R_AVR_6_ADIW         = 21 # :nodoc:
        R_AVR_MS8_LDI        = 22 # :nodoc:
        R_AVR_MS8_LDI_NEG    = 23 # :nodoc:
        R_AVR_LO8_LDI_GS     = 24 # :nodoc:
        R_AVR_HI8_LDI_GS     = 25 # :nodoc:
        R_AVR_8              = 26 # :nodoc:
        R_AVR_8_LO8          = 27 # :nodoc:
        R_AVR_8_HI8          = 28 # :nodoc:
        R_AVR_8_HLO8         = 29 # :nodoc:
        R_AVR_DIFF8          = 30 # :nodoc:
        R_AVR_DIFF16         = 31 # :nodoc:
        R_AVR_DIFF32         = 32 # :nodoc:
        R_AVR_LDS_STS_16     = 33 # :nodoc:
        R_AVR_PORT6          = 34 # :nodoc:
        R_AVR_PORT5          = 35 # :nodoc:
        R_AVR_32_PCREL       = 36 # :nodoc:
      end
    end
  end
end
