# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of BFIN.
      module BFIN
        R_BFIN_UNUSED0             = 0 # relocation type 0 is not defined
        R_BFIN_PCREL5M2            = 1 # LSETUP part a
        R_BFIN_UNUSED1             = 2 # relocation type 2 is not defined
        R_BFIN_PCREL10             = 3 # type 3, 0x00) if cc jump <target>
        R_BFIN_PCREL12_JUMP        = 4 # type 4, 0x00) jump <target>
        R_BFIN_RIMM16              = 5 # type 0x5, 0x00) rN = <target>
        R_BFIN_LUIMM16             = 6 # # 0x6, 0x00) preg.l=<target> Load imm 16 to lower half
        R_BFIN_HUIMM16             = 7 # # 0x7, 0x00) preg.h=<target> Load imm 16 to upper half
        R_BFIN_PCREL12_JUMP_S      = 8 # # 0x8 jump.s <target>
        R_BFIN_PCREL24_JUMP_X      = 9 # # 0x9 jump.x <target>
        R_BFIN_PCREL24             = 10 # # 0xa call <target> , 0x00) not expandable
        R_BFIN_UNUSEDB             = 11 # # 0xb not generated
        R_BFIN_UNUSEDC             = 12 # # 0xc not used
        R_BFIN_PCREL24_JUMP_L      = 13 # 0xd jump.l <target>
        R_BFIN_PCREL24_CALL_X      = 14 # 0xE, 0x00) call.x <target> if <target> is above 24 bit limit call through P1
        R_BFIN_VAR_EQ_SYMB         = 15 # 0xf, 0x00) linker should treat it same as 0x12
        R_BFIN_BYTE_DATA           = 16 # 0x10, 0x00) .byte var = symbol
        R_BFIN_BYTE2_DATA          = 17 # 0x11, 0x00) .byte2 var = symbol
        R_BFIN_BYTE4_DATA          = 18 # 0x12, 0x00) .byte4 var = symbol and .var var=symbol
        R_BFIN_PCREL11             = 19 # 0x13, 0x00) lsetup part b
        R_BFIN_GOT17M4             = 20 # :nodoc:
        R_BFIN_GOTHI               = 21 # :nodoc:
        R_BFIN_GOTLO               = 22 # :nodoc:
        R_BFIN_FUNCDESC            = 23 # :nodoc:
        R_BFIN_FUNCDESC_GOT17M4    = 24 # :nodoc:
        R_BFIN_FUNCDESC_GOTHI      = 25 # :nodoc:
        R_BFIN_FUNCDESC_GOTLO      = 26 # :nodoc:
        R_BFIN_FUNCDESC_VALUE      = 27 # :nodoc:
        R_BFIN_FUNCDESC_GOTOFF17M4 = 28 # :nodoc:
        R_BFIN_FUNCDESC_GOTOFFHI   = 29 # :nodoc:
        R_BFIN_FUNCDESC_GOTOFFLO   = 30 # :nodoc:
        R_BFIN_GOTOFF17M4          = 31 # :nodoc:
        R_BFIN_GOTOFFHI            = 32 # :nodoc:
        R_BFIN_GOTOFFLO            = 33 # :nodoc:
        R_BFIN_PLTPC               = 64 # PLT gnu only relocation
        R_BFIN_GOT                 = 65 # GOT gnu only relocation
        R_BFIN_GNU_VTINHERIT       = 66 # C++, gnu only
        R_BFIN_GNU_VTENTRY         = 67 # C++, gnu only
        R_BFIN_PUSH                = 224 # :nodoc:
        R_BFIN_CONST               = 225 # :nodoc:
        R_BFIN_ADD                 = 226 # :nodoc:
        R_BFIN_SUB                 = 227 # :nodoc:
        R_BFIN_MULT                = 228 # :nodoc:
        R_BFIN_DIV                 = 229 # :nodoc:
        R_BFIN_MOD                 = 230 # :nodoc:
        R_BFIN_LSHIFT              = 231 # :nodoc:
        R_BFIN_RSHIFT              = 232 # :nodoc:
        R_BFIN_AND                 = 233 # :nodoc:
        R_BFIN_OR                  = 234 # :nodoc:
        R_BFIN_XOR                 = 235 # :nodoc:
        R_BFIN_LAND                = 236 # :nodoc:
        R_BFIN_LOR                 = 237 # :nodoc:
        R_BFIN_LEN                 = 238 # :nodoc:
        R_BFIN_NEG                 = 239 # :nodoc:
        R_BFIN_COMP                = 240 # :nodoc:
        R_BFIN_PAGE                = 241 # :nodoc:
        R_BFIN_HWPAGE              = 242 # :nodoc:
        R_BFIN_ADDR                = 243 # :nodoc:
      end
    end
  end
end
