# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of BPF.
      module BPF
        R_BPF_NONE        = 0 # :nodoc:
        R_BPF_64_64       = 1 # :nodoc:
        R_BPF_64_ABS64    = 2 # :nodoc:
        R_BPF_64_ABS32    = 3 # :nodoc:
        R_BPF_64_NODYLD32 = 4 # :nodoc:
        R_BPF_64_32       = 10 # :nodoc:
        R_BPF_GNU_64_16   = 256 # :nodoc:
      end
    end
  end
end
