# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of CR16.
      module CR16
        R_CR16_NONE          = 0 # :nodoc:
        R_CR16_NUM8          = 1 # :nodoc:
        R_CR16_NUM16         = 2 # :nodoc:
        R_CR16_NUM32         = 3 # :nodoc:
        R_CR16_NUM32a        = 4 # :nodoc:
        R_CR16_REGREL4       = 5 # :nodoc:
        R_CR16_REGREL4a      = 6 # :nodoc:
        R_CR16_REGREL14      = 7 # :nodoc:
        R_CR16_REGREL14a     = 8 # :nodoc:
        R_CR16_REGREL16      = 9 # :nodoc:
        R_CR16_REGREL20      = 10 # :nodoc:
        R_CR16_REGREL20a     = 11 # :nodoc:
        R_CR16_ABS20         = 12 # :nodoc:
        R_CR16_ABS24         = 13 # :nodoc:
        R_CR16_IMM4          = 14 # :nodoc:
        R_CR16_IMM8          = 15 # :nodoc:
        R_CR16_IMM16         = 16 # :nodoc:
        R_CR16_IMM20         = 17 # :nodoc:
        R_CR16_IMM24         = 18 # :nodoc:
        R_CR16_IMM32         = 19 # :nodoc:
        R_CR16_IMM32a        = 20 # :nodoc:
        R_CR16_DISP4         = 21 # :nodoc:
        R_CR16_DISP8         = 22 # :nodoc:
        R_CR16_DISP16        = 23 # :nodoc:
        R_CR16_DISP24        = 24 # :nodoc:
        R_CR16_DISP24a       = 25 # :nodoc:
        R_CR16_SWITCH8       = 26 # :nodoc:
        R_CR16_SWITCH16      = 27 # :nodoc:
        R_CR16_SWITCH32      = 28 # :nodoc:
        R_CR16_GOT_REGREL20  = 29 # :nodoc:
        R_CR16_GOTC_REGREL20 = 30 # :nodoc:
        R_CR16_GLOB_DAT      = 31 # :nodoc:
      end
    end
  end
end
