# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of CRIS.
      module CRIS
        R_CRIS_NONE          = 0 # :nodoc:
        R_CRIS_8             = 1 # :nodoc:
        R_CRIS_16            = 2 # :nodoc:
        R_CRIS_32            = 3 # :nodoc:
        R_CRIS_8_PCREL       = 4 # :nodoc:
        R_CRIS_16_PCREL      = 5 # :nodoc:
        R_CRIS_32_PCREL      = 6 # :nodoc:
        R_CRIS_GNU_VTINHERIT = 7 # :nodoc:
        R_CRIS_GNU_VTENTRY   = 8 # :nodoc:
        R_CRIS_COPY          = 9 # :nodoc:
        R_CRIS_GLOB_DAT      = 10 # :nodoc:
        R_CRIS_JUMP_SLOT     = 11 # :nodoc:
        R_CRIS_RELATIVE      = 12 # :nodoc:
        R_CRIS_16_GOT        = 13 # :nodoc:
        R_CRIS_32_GOT        = 14 # :nodoc:
        R_CRIS_16_GOTPLT     = 15 # :nodoc:
        R_CRIS_32_GOTPLT     = 16 # :nodoc:
        R_CRIS_32_GOTREL     = 17 # :nodoc:
        R_CRIS_32_PLT_GOTREL = 18 # :nodoc:
        R_CRIS_32_PLT_PCREL  = 19 # :nodoc:
        R_CRIS_32_GOT_GD     = 20 # :nodoc:
        R_CRIS_16_GOT_GD     = 21 # :nodoc:
        R_CRIS_32_GD         = 22 # :nodoc:
        R_CRIS_DTP           = 23 # :nodoc:
        R_CRIS_32_DTPREL     = 24 # :nodoc:
        R_CRIS_16_DTPREL     = 25 # :nodoc:
        R_CRIS_32_GOT_TPREL  = 26 # :nodoc:
        R_CRIS_16_GOT_TPREL  = 27 # :nodoc:
        R_CRIS_32_TPREL      = 28 # :nodoc:
        R_CRIS_16_TPREL      = 29 # :nodoc:
        R_CRIS_DTPMOD        = 30 # :nodoc:
        R_CRIS_32_IE         = 31 # :nodoc:
      end
    end
  end
end
