# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of CRX.
      module CRX
        R_CRX_NONE     = 0 # :nodoc:
        R_CRX_REL4     = 1 # :nodoc:
        R_CRX_REL8     = 2 # :nodoc:
        R_CRX_REL8_CMP = 3 # :nodoc:
        R_CRX_REL16    = 4 # :nodoc:
        R_CRX_REL24    = 5 # :nodoc:
        R_CRX_REL32    = 6 # :nodoc:
        R_CRX_REGREL12 = 7 # :nodoc:
        R_CRX_REGREL22 = 8 # :nodoc:
        R_CRX_REGREL28 = 9 # :nodoc:
        R_CRX_REGREL32 = 10 # :nodoc:
        R_CRX_ABS16    = 11 # :nodoc:
        R_CRX_ABS32    = 12 # :nodoc:
        R_CRX_NUM8     = 13 # :nodoc:
        R_CRX_NUM16    = 14 # :nodoc:
        R_CRX_NUM32    = 15 # :nodoc:
        R_CRX_IMM16    = 16 # :nodoc:
        R_CRX_IMM32    = 17 # :nodoc:
        R_CRX_SWITCH8  = 18 # :nodoc:
        R_CRX_SWITCH16 = 19 # :nodoc:
        R_CRX_SWITCH32 = 20 # :nodoc:
      end
    end
  end
end
