# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of CSKY.
      module CSKY
        R_CKCORE_NONE                 = 0 # :nodoc:
        R_CKCORE_ADDR32               = 1 # :nodoc:
        R_CKCORE_PCREL_IMM8BY4        = 2 # :nodoc:
        R_CKCORE_PCREL_IMM11BY2       = 3 # :nodoc:
        R_CKCORE_PCREL_IMM4BY2        = 4 # :nodoc:
        R_CKCORE_PCREL32              = 5 # :nodoc:
        R_CKCORE_PCREL_JSR_IMM11BY2   = 6 # :nodoc:
        R_CKCORE_GNU_VTINHERIT        = 7 # :nodoc:
        R_CKCORE_GNU_VTENTRY          = 8 # :nodoc:
        R_CKCORE_RELATIVE             = 9 # :nodoc:
        R_CKCORE_COPY                 = 10 # :nodoc:
        R_CKCORE_GLOB_DAT             = 11 # :nodoc:
        R_CKCORE_JUMP_SLOT            = 12 # :nodoc:
        R_CKCORE_GOTOFF               = 13 # :nodoc:
        R_CKCORE_GOTPC                = 14 # :nodoc:
        R_CKCORE_GOT32                = 15 # :nodoc:
        R_CKCORE_PLT32                = 16 # :nodoc:
        R_CKCORE_ADDRGOT              = 17 # :nodoc:
        R_CKCORE_ADDRPLT              = 18 # :nodoc:
        R_CKCORE_PCREL_IMM26BY2       = 19 # :nodoc:
        R_CKCORE_PCREL_IMM16BY2       = 20 # :nodoc:
        R_CKCORE_PCREL_IMM16BY4       = 21 # :nodoc:
        R_CKCORE_PCREL_IMM10BY2       = 22 # :nodoc:
        R_CKCORE_PCREL_IMM10BY4       = 23 # :nodoc:
        R_CKCORE_ADDR_HI16            = 24 # :nodoc:
        R_CKCORE_ADDR_LO16            = 25 # :nodoc:
        R_CKCORE_GOTPC_HI16           = 26 # :nodoc:
        R_CKCORE_GOTPC_LO16           = 27 # :nodoc:
        R_CKCORE_GOTOFF_HI16          = 28 # :nodoc:
        R_CKCORE_GOTOFF_LO16          = 29 # :nodoc:
        R_CKCORE_GOT12                = 30 # :nodoc:
        R_CKCORE_GOT_HI16             = 31 # :nodoc:
        R_CKCORE_GOT_LO16             = 32 # :nodoc:
        R_CKCORE_PLT12                = 33 # :nodoc:
        R_CKCORE_PLT_HI16             = 34 # :nodoc:
        R_CKCORE_PLT_LO16             = 35 # :nodoc:
        R_CKCORE_ADDRGOT_HI16         = 36 # :nodoc:
        R_CKCORE_ADDRGOT_LO16         = 37 # :nodoc:
        R_CKCORE_ADDRPLT_HI16         = 38 # :nodoc:
        R_CKCORE_ADDRPLT_LO16         = 39 # :nodoc:
        R_CKCORE_PCREL_JSR_IMM26BY2   = 40 # :nodoc:
        R_CKCORE_TOFFSET_LO16         = 41 # :nodoc:
        R_CKCORE_DOFFSET_LO16         = 42 # :nodoc:
        R_CKCORE_PCREL_IMM18BY2       = 43 # :nodoc:
        R_CKCORE_DOFFSET_IMM18        = 44 # :nodoc:
        R_CKCORE_DOFFSET_IMM18BY2     = 45 # :nodoc:
        R_CKCORE_DOFFSET_IMM18BY4     = 46 # :nodoc:
        R_CKCORE_GOTOFF_IMM18         = 47 # :nodoc:
        R_CKCORE_GOT_IMM18BY4         = 48 # :nodoc:
        R_CKCORE_PLT_IMM18BY4         = 49 # :nodoc:
        R_CKCORE_PCREL_IMM7BY4        = 50 # :nodoc:
        R_CKCORE_TLS_LE32             = 51 # :nodoc:
        R_CKCORE_TLS_IE32             = 52 # :nodoc:
        R_CKCORE_TLS_GD32             = 53 # :nodoc:
        R_CKCORE_TLS_LDM32            = 54 # :nodoc:
        R_CKCORE_TLS_LDO32            = 55 # :nodoc:
        R_CKCORE_TLS_DTPMOD32         = 56 # :nodoc:
        R_CKCORE_TLS_DTPOFF32         = 57 # :nodoc:
        R_CKCORE_TLS_TPOFF32          = 58 # :nodoc:
        R_CKCORE_PCREL_FLRW_IMM8BY4   = 59 # :nodoc:
        R_CKCORE_NOJSRI               = 60 # :nodoc:
        R_CKCORE_CALLGRAPH            = 61 # :nodoc:
        R_CKCORE_IRELATIVE            = 62 # :nodoc:
        R_CKCORE_PCREL_BLOOP_IMM4BY4  = 63 # :nodoc:
        R_CKCORE_PCREL_BLOOP_IMM12BY4 = 64 # :nodoc:
      end
    end
  end
end
