# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of D10V.
      module D10V
        R_D10V_NONE          = 0 # :nodoc:
        R_D10V_10_PCREL_R    = 1 # :nodoc:
        R_D10V_10_PCREL_L    = 2 # :nodoc:
        R_D10V_16            = 3 # :nodoc:
        R_D10V_18            = 4 # :nodoc:
        R_D10V_18_PCREL      = 5 # :nodoc:
        R_D10V_32            = 6 # :nodoc:
        R_D10V_GNU_VTINHERIT = 7 # :nodoc:
        R_D10V_GNU_VTENTRY   = 8 # :nodoc:
      end
    end
  end
end
