# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of D30V.
      module D30V
        R_D30V_NONE       = 0 # :nodoc:
        R_D30V_6          = 1 # :nodoc:
        R_D30V_9_PCREL    = 2 # :nodoc:
        R_D30V_9_PCREL_R  = 3 # :nodoc:
        R_D30V_15         = 4 # :nodoc:
        R_D30V_15_PCREL   = 5 # :nodoc:
        R_D30V_15_PCREL_R = 6 # :nodoc:
        R_D30V_21         = 7 # :nodoc:
        R_D30V_21_PCREL   = 8 # :nodoc:
        R_D30V_21_PCREL_R = 9 # :nodoc:
        R_D30V_32         = 10 # :nodoc:
        R_D30V_32_PCREL   = 11 # :nodoc:
        R_D30V_32_NORMAL  = 12 # :nodoc:
      end
    end
  end
end
