# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of DLX.
      module DLX
        R_DLX_NONE           = 0 # :nodoc:
        R_DLX_RELOC_8        = 1 # :nodoc:
        R_DLX_RELOC_16       = 2 # :nodoc:
        R_DLX_RELOC_32       = 3 # :nodoc:
        R_DLX_GNU_VTINHERIT  = 4 # :nodoc:
        R_DLX_GNU_VTENTRY    = 5 # :nodoc:
        R_DLX_RELOC_16_HI    = 6 # :nodoc:
        R_DLX_RELOC_16_LO    = 7 # :nodoc:
        R_DLX_RELOC_16_PCREL = 8 # :nodoc:
        R_DLX_RELOC_26_PCREL = 9 # :nodoc:
      end
    end
  end
end
