# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of EPIPHANY.
      module EPIPHANY
        R_EPIPHANY_NONE     = 0 # :nodoc:
        R_EPIPHANY_8        = 1 # :nodoc:
        R_EPIPHANY_16       = 2 # :nodoc:
        R_EPIPHANY_32       = 3 # :nodoc:
        R_EPIPHANY_8_PCREL  = 4 # :nodoc:
        R_EPIPHANY_16_PCREL = 5 # :nodoc:
        R_EPIPHANY_32_PCREL = 6 # :nodoc:
        R_EPIPHANY_SIMM8    = 7 # :nodoc:
        R_EPIPHANY_SIMM24   = 8 # :nodoc:
        R_EPIPHANY_HIGH     = 9 # :nodoc:
        R_EPIPHANY_LOW      = 10 # :nodoc:
        R_EPIPHANY_SIMM11   = 11 # :nodoc:
        R_EPIPHANY_IMM11    = 12 # :nodoc:
        R_EPIPHANY_IMM8     = 13 # :nodoc:
      end
    end
  end
end
