# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of FR30.
      module FR30
        R_FR30_NONE          = 0 # :nodoc:
        R_FR30_8             = 1 # :nodoc:
        R_FR30_20            = 2 # :nodoc:
        R_FR30_32            = 3 # :nodoc:
        R_FR30_48            = 4 # :nodoc:
        R_FR30_6_IN_4        = 5 # :nodoc:
        R_FR30_8_IN_8        = 6 # :nodoc:
        R_FR30_9_IN_8        = 7 # :nodoc:
        R_FR30_10_IN_8       = 8 # :nodoc:
        R_FR30_9_PCREL       = 9 # :nodoc:
        R_FR30_12_PCREL      = 10 # :nodoc:
        R_FR30_GNU_VTINHERIT = 11 # :nodoc:
        R_FR30_GNU_VTENTRY   = 12 # :nodoc:
      end
    end
  end
end
