# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of FRV.
      module FRV
        R_FRV_NONE              = 0 # :nodoc:
        R_FRV_32                = 1 # :nodoc:
        R_FRV_LABEL16           = 2 # :nodoc:
        R_FRV_LABEL24           = 3 # :nodoc:
        R_FRV_LO16              = 4 # :nodoc:
        R_FRV_HI16              = 5 # :nodoc:
        R_FRV_GPREL12           = 6 # :nodoc:
        R_FRV_GPRELU12          = 7 # :nodoc:
        R_FRV_GPREL32           = 8 # :nodoc:
        R_FRV_GPRELHI           = 9 # :nodoc:
        R_FRV_GPRELLO           = 10 # :nodoc:
        R_FRV_GOT12             = 11 # :nodoc:
        R_FRV_GOTHI             = 12 # :nodoc:
        R_FRV_GOTLO             = 13 # :nodoc:
        R_FRV_FUNCDESC          = 14 # :nodoc:
        R_FRV_FUNCDESC_GOT12    = 15 # :nodoc:
        R_FRV_FUNCDESC_GOTHI    = 16 # :nodoc:
        R_FRV_FUNCDESC_GOTLO    = 17 # :nodoc:
        R_FRV_FUNCDESC_VALUE    = 18 # :nodoc:
        R_FRV_FUNCDESC_GOTOFF12 = 19 # :nodoc:
        R_FRV_FUNCDESC_GOTOFFHI = 20 # :nodoc:
        R_FRV_FUNCDESC_GOTOFFLO = 21 # :nodoc:
        R_FRV_GOTOFF12          = 22 # :nodoc:
        R_FRV_GOTOFFHI          = 23 # :nodoc:
        R_FRV_GOTOFFLO          = 24 # :nodoc:
        R_FRV_GETTLSOFF         = 25 # :nodoc:
        R_FRV_TLSDESC_VALUE     = 26 # :nodoc:
        R_FRV_GOTTLSDESC12      = 27 # :nodoc:
        R_FRV_GOTTLSDESCHI      = 28 # :nodoc:
        R_FRV_GOTTLSDESCLO      = 29 # :nodoc:
        R_FRV_TLSMOFF12         = 30 # :nodoc:
        R_FRV_TLSMOFFHI         = 31 # :nodoc:
        R_FRV_TLSMOFFLO         = 32 # :nodoc:
        R_FRV_GOTTLSOFF12       = 33 # :nodoc:
        R_FRV_GOTTLSOFFHI       = 34 # :nodoc:
        R_FRV_GOTTLSOFFLO       = 35 # :nodoc:
        R_FRV_TLSOFF            = 36 # :nodoc:
        R_FRV_TLSDESC_RELAX     = 37 # :nodoc:
        R_FRV_GETTLSOFF_RELAX   = 38 # :nodoc:
        R_FRV_TLSOFF_RELAX      = 39 # :nodoc:
        R_FRV_TLSMOFF           = 40 # :nodoc:
        R_FRV_GNU_VTINHERIT     = 200 # :nodoc:
        R_FRV_GNU_VTENTRY       = 201 # :nodoc:
      end
    end
  end
end
