# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of FT32.
      module FT32
        R_FT32_NONE   = 0 # :nodoc:
        R_FT32_32     = 1 # :nodoc:
        R_FT32_16     = 2 # :nodoc:
        R_FT32_8      = 3 # :nodoc:
        R_FT32_10     = 4 # :nodoc:
        R_FT32_20     = 5 # :nodoc:
        R_FT32_17     = 6 # :nodoc:
        R_FT32_18     = 7 # :nodoc:
        R_FT32_RELAX  = 8 # :nodoc:
        R_FT32_SC0    = 9 # :nodoc:
        R_FT32_SC1    = 10 # :nodoc:
        R_FT32_15     = 11 # :nodoc:
        R_FT32_DIFF32 = 12 # :nodoc:
      end
    end
  end
end
