# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of H8.
      module H8
        R_H8_NONE      = 0 # :nodoc:
        R_H8_DIR32     = 1 # :nodoc:
        R_H8_DIR32_28  = 2 # :nodoc:
        R_H8_DIR32_24  = 3 # :nodoc:
        R_H8_DIR32_16  = 4 # :nodoc:
        R_H8_DIR32U    = 6 # :nodoc:
        R_H8_DIR32U_28 = 7 # :nodoc:
        R_H8_DIR32U_24 = 8 # :nodoc:
        R_H8_DIR32U_20 = 9 # :nodoc:
        R_H8_DIR32U_16 = 10 # :nodoc:
        R_H8_DIR24     = 11 # :nodoc:
        R_H8_DIR24_20  = 12 # :nodoc:
        R_H8_DIR24_16  = 13 # :nodoc:
        R_H8_DIR24U    = 14 # :nodoc:
        R_H8_DIR24U_20 = 15 # :nodoc:
        R_H8_DIR24U_16 = 16 # :nodoc:
        R_H8_DIR16     = 17 # :nodoc:
        R_H8_DIR16U    = 18 # :nodoc:
        R_H8_DIR16S_32 = 19 # :nodoc:
        R_H8_DIR16S_28 = 20 # :nodoc:
        R_H8_DIR16S_24 = 21 # :nodoc:
        R_H8_DIR16S_20 = 22 # :nodoc:
        R_H8_DIR16S    = 23 # :nodoc:
        R_H8_DIR8      = 24 # :nodoc:
        R_H8_DIR8U     = 25 # :nodoc:
        R_H8_DIR8Z_32  = 26 # :nodoc:
        R_H8_DIR8Z_28  = 27 # :nodoc:
        R_H8_DIR8Z_24  = 28 # :nodoc:
        R_H8_DIR8Z_20  = 29 # :nodoc:
        R_H8_DIR8Z_16  = 30 # :nodoc:
        R_H8_PCREL16   = 31 # :nodoc:
        R_H8_PCREL8    = 32 # :nodoc:
        R_H8_BPOS      = 33 # :nodoc:
        R_H8_DIR16A8   = 59 # :nodoc:
        R_H8_DIR16R8   = 60 # :nodoc:
        R_H8_DIR24A8   = 61 # :nodoc:
        R_H8_DIR24R8   = 62 # :nodoc:
        R_H8_DIR32A16  = 63 # :nodoc:
        R_H8_DISP32A16 = 64 # :nodoc:
        R_H8_ABS32     = 65 # :nodoc:
        R_H8_ABS32A16  = 127 # :nodoc:
        R_H8_SYM       = 128 # :nodoc:
        R_H8_OPneg     = 129 # :nodoc:
        R_H8_OPadd     = 130 # :nodoc:
        R_H8_OPsub     = 131 # :nodoc:
        R_H8_OPmul     = 132 # :nodoc:
        R_H8_OPdiv     = 133 # :nodoc:
        R_H8_OPshla    = 134 # :nodoc:
        R_H8_OPshra    = 135 # :nodoc:
        R_H8_OPsctsize = 136 # :nodoc:
        R_H8_OPhword   = 137 # :nodoc:
        R_H8_OPlword   = 138 # :nodoc:
        R_H8_OPhigh    = 139 # :nodoc:
        R_H8_OPlow     = 140 # :nodoc:
        R_H8_OPscttop  = 141 # :nodoc:
      end
    end
  end
end
