# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of HPPA.
      module HPPA
        R_PARISC_NONE           = 0 # No reloc
        R_PARISC_DIR32          = 1 # :nodoc:
        R_PARISC_DIR21L         = 2 # :nodoc:
        R_PARISC_DIR17R         = 3 # :nodoc:
        R_PARISC_DIR17F         = 4 # :nodoc:
        R_PARISC_DIR14R         = 6 # :nodoc:
        R_PARISC_DIR14F         = 7 # :nodoc:
        R_PARISC_PCREL12F       = 8 # :nodoc:
        R_PARISC_PCREL32        = 9 # :nodoc:
        R_PARISC_PCREL21L       = 10 # :nodoc:
        R_PARISC_PCREL17R       = 11 # :nodoc:
        R_PARISC_PCREL17F       = 12 # :nodoc:
        R_PARISC_PCREL17C       = 13 # :nodoc:
        R_PARISC_PCREL14R       = 14 # :nodoc:
        R_PARISC_PCREL14F       = 15 # :nodoc:
        R_PARISC_DPREL21L       = 18 # :nodoc:
        R_PARISC_DPREL14WR      = 19 # :nodoc:
        R_PARISC_DPREL14DR      = 20 # :nodoc:
        R_PARISC_DPREL14R       = 22 # :nodoc:
        R_PARISC_DPREL14F       = 23 # :nodoc:
        R_PARISC_DLTREL21L      = 26 # :nodoc:
        R_PARISC_DLTREL14R      = 30 # :nodoc:
        R_PARISC_DLTREL14F      = 31 # :nodoc:
        R_PARISC_DLTIND21L      = 34 # :nodoc:
        R_PARISC_DLTIND14R      = 38 # :nodoc:
        R_PARISC_DLTIND14F      = 39 # :nodoc:
        R_PARISC_SETBASE        = 40 # :nodoc:
        R_PARISC_SECREL32       = 41 # :nodoc:
        R_PARISC_BASEREL21L     = 42 # :nodoc:
        R_PARISC_BASEREL17R     = 43 # :nodoc:
        R_PARISC_BASEREL17F     = 44 # :nodoc:
        R_PARISC_BASEREL14R     = 46 # :nodoc:
        R_PARISC_BASEREL14F     = 47 # :nodoc:
        R_PARISC_SEGBASE        = 48 # :nodoc:
        R_PARISC_SEGREL32       = 49 # :nodoc:
        R_PARISC_PLTOFF21L      = 50 # :nodoc:
        R_PARISC_PLTOFF14R      = 54 # :nodoc:
        R_PARISC_PLTOFF14F      = 55 # :nodoc:
        R_PARISC_LTOFF_FPTR32   = 57 # :nodoc:
        R_PARISC_LTOFF_FPTR21L  = 58 # :nodoc:
        R_PARISC_LTOFF_FPTR14R  = 62 # :nodoc:
        R_PARISC_FPTR64         = 64 # :nodoc:
        R_PARISC_PLABEL32       = 65 # :nodoc:
        R_PARISC_PLABEL21L      = 66 # :nodoc:
        R_PARISC_PLABEL14R      = 70 # :nodoc:
        R_PARISC_PCREL64        = 72 # :nodoc:
        R_PARISC_PCREL22C       = 73 # :nodoc:
        R_PARISC_PCREL22F       = 74 # :nodoc:
        R_PARISC_PCREL14WR      = 75 # :nodoc:
        R_PARISC_PCREL14DR      = 76 # :nodoc:
        R_PARISC_PCREL16F       = 77 # :nodoc:
        R_PARISC_PCREL16WF      = 78 # :nodoc:
        R_PARISC_PCREL16DF      = 79 # :nodoc:
        R_PARISC_DIR64          = 80 # :nodoc:
        R_PARISC_DIR14WR        = 83 # :nodoc:
        R_PARISC_DIR14DR        = 84 # :nodoc:
        R_PARISC_DIR16F         = 85 # :nodoc:
        R_PARISC_DIR16WF        = 86 # :nodoc:
        R_PARISC_DIR16DF        = 87 # :nodoc:
        R_PARISC_GPREL64        = 88 # :nodoc:
        R_PARISC_DLTREL14WR     = 91 # :nodoc:
        R_PARISC_DLTREL14DR     = 92 # :nodoc:
        R_PARISC_GPREL16F       = 93 # :nodoc:
        R_PARISC_GPREL16WF      = 94 # :nodoc:
        R_PARISC_GPREL16DF      = 95 # :nodoc:
        R_PARISC_LTOFF64        = 96 # :nodoc:
        R_PARISC_DLTIND14WR     = 99 # :nodoc:
        R_PARISC_DLTIND14DR     = 100 # :nodoc:
        R_PARISC_LTOFF16F       = 101 # :nodoc:
        R_PARISC_LTOFF16WF      = 102 # :nodoc:
        R_PARISC_LTOFF16DF      = 103 # :nodoc:
        R_PARISC_SECREL64       = 104 # :nodoc:
        R_PARISC_BASEREL14WR    = 107 # :nodoc:
        R_PARISC_BASEREL14DR    = 108 # :nodoc:
        R_PARISC_SEGREL64       = 112 # :nodoc:
        R_PARISC_PLTOFF14WR     = 115 # :nodoc:
        R_PARISC_PLTOFF14DR     = 116 # :nodoc:
        R_PARISC_PLTOFF16F      = 117 # :nodoc:
        R_PARISC_PLTOFF16WF     = 118 # :nodoc:
        R_PARISC_PLTOFF16DF     = 119 # :nodoc:
        R_PARISC_LTOFF_FPTR64   = 120 # :nodoc:
        R_PARISC_LTOFF_FPTR14WR = 123 # :nodoc:
        R_PARISC_LTOFF_FPTR14DR = 124 # :nodoc:
        R_PARISC_LTOFF_FPTR16F  = 125 # :nodoc:
        R_PARISC_LTOFF_FPTR16WF = 126 # :nodoc:
        R_PARISC_LTOFF_FPTR16DF = 127 # :nodoc:
        R_PARISC_COPY           = 128 # :nodoc:
        R_PARISC_IPLT           = 129 # :nodoc:
        R_PARISC_EPLT           = 130 # :nodoc:
        R_PARISC_TPREL32        = 153 # :nodoc:
        R_PARISC_TPREL21L       = 154 # :nodoc:
        R_PARISC_TPREL14R       = 158 # :nodoc:
        R_PARISC_LTOFF_TP21L    = 162 # :nodoc:
        R_PARISC_LTOFF_TP14R    = 166 # :nodoc:
        R_PARISC_LTOFF_TP14F    = 167 # :nodoc:
        R_PARISC_TPREL64        = 216 # :nodoc:
        R_PARISC_TPREL14WR      = 219 # :nodoc:
        R_PARISC_TPREL14DR      = 220 # :nodoc:
        R_PARISC_TPREL16F       = 221 # :nodoc:
        R_PARISC_TPREL16WF      = 222 # :nodoc:
        R_PARISC_TPREL16DF      = 223 # :nodoc:
        R_PARISC_LTOFF_TP64     = 224 # :nodoc:
        R_PARISC_LTOFF_TP14WR   = 227 # :nodoc:
        R_PARISC_LTOFF_TP14DR   = 228 # :nodoc:
        R_PARISC_LTOFF_TP16F    = 229 # :nodoc:
        R_PARISC_LTOFF_TP16WF   = 230 # :nodoc:
        R_PARISC_LTOFF_TP16DF   = 231 # :nodoc:
        R_PARISC_GNU_VTENTRY    = 232 # :nodoc:
        R_PARISC_GNU_VTINHERIT  = 233 # :nodoc:
        R_PARISC_TLS_GD21L      = 234 # :nodoc:
        R_PARISC_TLS_GD14R      = 235 # :nodoc:
        R_PARISC_TLS_GDCALL     = 236 # :nodoc:
        R_PARISC_TLS_LDM21L     = 237 # :nodoc:
        R_PARISC_TLS_LDM14R     = 238 # :nodoc:
        R_PARISC_TLS_LDMCALL    = 239 # :nodoc:
        R_PARISC_TLS_LDO21L     = 240 # :nodoc:
        R_PARISC_TLS_LDO14R     = 241 # :nodoc:
        R_PARISC_TLS_DTPMOD32   = 242 # :nodoc:
        R_PARISC_TLS_DTPMOD64   = 243 # :nodoc:
        R_PARISC_TLS_DTPOFF32   = 244 # :nodoc:
        R_PARISC_TLS_DTPOFF64   = 245 # :nodoc:
      end
    end
  end
end
