# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of I370.
      module I370
        R_I370_NONE     = 0 # :nodoc:
        R_I370_ADDR31   = 1 # :nodoc:
        R_I370_ADDR32   = 2 # :nodoc:
        R_I370_ADDR16   = 3 # :nodoc:
        R_I370_REL31    = 4 # :nodoc:
        R_I370_REL32    = 5 # :nodoc:
        R_I370_ADDR12   = 6 # :nodoc:
        R_I370_REL12    = 7 # :nodoc:
        R_I370_ADDR8    = 8 # :nodoc:
        R_I370_REL8     = 9 # :nodoc:
        R_I370_COPY     = 10 # :nodoc:
        R_I370_RELATIVE = 11 # :nodoc:
      end
    end
  end
end
