# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of I386.
      module I386
        R_386_NONE              = 0 # No reloc
        R_386_32                = 1 # Direct 32 bit
        R_386_PC32              = 2 # PC relative 32 bit
        R_386_GOT32             = 3 # 32 bit GOT entry
        R_386_PLT32             = 4 # 32 bit PLT address
        R_386_COPY              = 5 # Copy symbol at runtime
        R_386_GLOB_DAT          = 6 # Create GOT entry
        R_386_JUMP_SLOT         = 7 # Create PLT entry
        R_386_RELATIVE          = 8 # Adjust by program base
        R_386_GOTOFF            = 9 # 32 bit offset to GOT
        R_386_GOTPC             = 10 # 32 bit PC relative offset to GOT
        R_386_32PLT             = 11 # Used by Sun
        R_386_TLS_TPOFF         = 14 # :nodoc:
        R_386_TLS_IE            = 15 # :nodoc:
        R_386_TLS_GOTIE         = 16 # :nodoc:
        R_386_TLS_LE            = 17 # :nodoc:
        R_386_TLS_GD            = 18 # :nodoc:
        R_386_TLS_LDM           = 19 # :nodoc:
        R_386_16                = 20 # :nodoc:
        R_386_PC16              = 21 # :nodoc:
        R_386_8                 = 22 # :nodoc:
        R_386_PC8               = 23 # :nodoc:
        R_386_TLS_GD_32         = 24 # :nodoc:
        R_386_TLS_GD_PUSH       = 25 # :nodoc:
        R_386_TLS_GD_CALL       = 26 # :nodoc:
        R_386_TLS_GD_POP        = 27 # :nodoc:
        R_386_TLS_LDM_32        = 28 # :nodoc:
        R_386_TLS_LDM_PUSH      = 29 # :nodoc:
        R_386_TLS_LDM_CALL      = 30 # :nodoc:
        R_386_TLS_LDM_POP       = 31 # :nodoc:
        R_386_TLS_LDO_32        = 32 # :nodoc:
        R_386_TLS_IE_32         = 33 # :nodoc:
        R_386_TLS_LE_32         = 34 # :nodoc:
        R_386_TLS_DTPMOD32      = 35 # :nodoc:
        R_386_TLS_DTPOFF32      = 36 # :nodoc:
        R_386_TLS_TPOFF32       = 37 # :nodoc:
        R_386_SIZE32            = 38 # 32-bit symbol size
        R_386_TLS_GOTDESC       = 39 # :nodoc:
        R_386_TLS_DESC_CALL     = 40 # :nodoc:
        R_386_TLS_DESC          = 41 # :nodoc:
        R_386_IRELATIVE         = 42 # Adjust indirectly by program base
        R_386_GOT32X            = 43 # :nodoc:
        R_386_USED_BY_INTEL_200 = 200 # :nodoc:
        R_386_GNU_VTINHERIT     = 250 # :nodoc:
        R_386_GNU_VTENTRY       = 251 # :nodoc:
      end
    end
  end
end
