# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of I860.
      module I860
        R_860_NONE      = 0 # No reloc
        R_860_32        = 1 # S+A
        R_860_COPY      = 2 # No calculation
        R_860_GLOB_DAT  = 3 # S, Create GOT entry
        R_860_JUMP_SLOT = 4 # S+A, Create PLT entry
        R_860_RELATIVE  = 5 # B+A, Adj by program base
        R_860_PC26      = 48 # (S+A-P) >> 2
        R_860_PLT26     = 49 # (L+A-P) >> 2
        R_860_PC16      = 50 # (S+A-P) >> 2
        R_860_LOW0      = 64 # S+A
        R_860_SPLIT0    = 66 # S+A
        R_860_LOW1      = 68 # S+A
        R_860_SPLIT1    = 70 # S+A
        R_860_LOW2      = 72 # S+A
        R_860_SPLIT2    = 74 # S+A
        R_860_LOW3      = 76 # S+A
        R_860_LOGOT0    = 80 # G
        R_860_SPGOT0    = 82 # G
        R_860_LOGOT1    = 84 # G
        R_860_SPGOT1    = 86 # G
        R_860_LOGOTOFF0 = 96 # O
        R_860_SPGOTOFF0 = 98 # O
        R_860_LOGOTOFF1 = 100 # O
        R_860_SPGOTOFF1 = 102 # O
        R_860_LOGOTOFF2 = 104 # O
        R_860_LOGOTOFF3 = 108 # O
        R_860_LOPC      = 112 # (S+A-P) >> 2
        R_860_HIGHADJ   = 128 # hiadj(S+A)
        R_860_HAGOT     = 144 # hiadj(G)
        R_860_HAGOTOFF  = 160 # hiadj(O)
        R_860_HAPC      = 176 # hiadj((S+A-P) >> 2)
        R_860_HIGH      = 192 # (S+A) >> 16
        R_860_HIGOT     = 208 # G >> 16
        R_860_HIGOTOFF  = 224 # O
      end
    end
  end
end
