# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of I960.
      module I960
        R_960_NONE      = 0 # :nodoc:
        R_960_12        = 1 # :nodoc:
        R_960_32        = 2 # :nodoc:
        R_960_IP24      = 3 # :nodoc:
        R_960_SUB       = 4 # :nodoc:
        R_960_OPTCALL   = 5 # :nodoc:
        R_960_OPTCALLX  = 6 # :nodoc:
        R_960_OPTCALLXA = 7 # :nodoc:
      end
    end
  end
end
