# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of IA64.
      module IA64
        R_IA64_NONE               = 0 # none
        R_IA64_IMM14              = 33 # symbol + addend, add imm14
        R_IA64_IMM22              = 34 # symbol + addend, add imm22
        R_IA64_IMM64              = 35 # symbol + addend, mov imm64
        R_IA64_DIR32MSB           = 36 # symbol + addend, data4 MSB
        R_IA64_DIR32LSB           = 37 # symbol + addend, data4 LSB
        R_IA64_DIR64MSB           = 38 # symbol + addend, data8 MSB
        R_IA64_DIR64LSB           = 39 # symbol + addend, data8 LSB
        R_IA64_GPREL22            = 42 # @gprel(sym+add), add imm22
        R_IA64_GPREL64I           = 43 # @gprel(sym+add), mov imm64
        R_IA64_GPREL32MSB         = 44 # @gprel(sym+add), data4 MSB
        R_IA64_GPREL32LSB         = 45 # @gprel(sym+add), data4 LSB
        R_IA64_GPREL64MSB         = 46 # @gprel(sym+add), data8 MSB
        R_IA64_GPREL64LSB         = 47 # @gprel(sym+add), data8 LSB
        R_IA64_LTOFF22            = 50 # @ltoff(sym+add), add imm22
        R_IA64_LTOFF64I           = 51 # @ltoff(sym+add), mov imm64
        R_IA64_PLTOFF22           = 58 # @pltoff(sym+add), add imm22
        R_IA64_PLTOFF64I          = 59 # @pltoff(sym+add), mov imm64
        R_IA64_PLTOFF64MSB        = 62 # @pltoff(sym+add), data8 MSB
        R_IA64_PLTOFF64LSB        = 63 # @pltoff(sym+add), data8 LSB
        R_IA64_FPTR64I            = 67 # @fptr(sym+add), mov imm64
        R_IA64_FPTR32MSB          = 68 # @fptr(sym+add), data4 MSB
        R_IA64_FPTR32LSB          = 69 # @fptr(sym+add), data4 LSB
        R_IA64_FPTR64MSB          = 70 # @fptr(sym+add), data8 MSB
        R_IA64_FPTR64LSB          = 71 # @fptr(sym+add), data8 LSB
        R_IA64_PCREL60B           = 72 # @pcrel(sym+add), brl
        R_IA64_PCREL21B           = 73 # @pcrel(sym+add), ptb, call
        R_IA64_PCREL21M           = 74 # @pcrel(sym+add), chk.s
        R_IA64_PCREL21F           = 75 # @pcrel(sym+add), fchkf
        R_IA64_PCREL32MSB         = 76 # @pcrel(sym+add), data4 MSB
        R_IA64_PCREL32LSB         = 77 # @pcrel(sym+add), data4 LSB
        R_IA64_PCREL64MSB         = 78 # @pcrel(sym+add), data8 MSB
        R_IA64_PCREL64LSB         = 79 # @pcrel(sym+add), data8 LSB
        R_IA64_LTOFF_FPTR22       = 82 # @ltoff(@fptr(s+a)), imm22
        R_IA64_LTOFF_FPTR64I      = 83 # @ltoff(@fptr(s+a)), imm64
        R_IA64_LTOFF_FPTR32MSB    = 84 # @ltoff(@fptr(s+a)), 4 MSB
        R_IA64_LTOFF_FPTR32LSB    = 85 # @ltoff(@fptr(s+a)), 4 LSB
        R_IA64_LTOFF_FPTR64MSB    = 86 # @ltoff(@fptr(s+a)), 8 MSB
        R_IA64_LTOFF_FPTR64LSB    = 87 # @ltoff(@fptr(s+a)), 8 LSB
        R_IA64_SEGREL32MSB        = 92 # @segrel(sym+add), data4 MSB
        R_IA64_SEGREL32LSB        = 93 # @segrel(sym+add), data4 LSB
        R_IA64_SEGREL64MSB        = 94 # @segrel(sym+add), data8 MSB
        R_IA64_SEGREL64LSB        = 95 # @segrel(sym+add), data8 LSB
        R_IA64_SECREL32MSB        = 100 # @secrel(sym+add), data4 MSB
        R_IA64_SECREL32LSB        = 101 # @secrel(sym+add), data4 LSB
        R_IA64_SECREL64MSB        = 102 # @secrel(sym+add), data8 MSB
        R_IA64_SECREL64LSB        = 103 # @secrel(sym+add), data8 LSB
        R_IA64_REL32MSB           = 108 # data 4 + REL
        R_IA64_REL32LSB           = 109 # data 4 + REL
        R_IA64_REL64MSB           = 110 # data 8 + REL
        R_IA64_REL64LSB           = 111 # data 8 + REL
        R_IA64_LTV32MSB           = 116 # symbol + addend, data4 MSB
        R_IA64_LTV32LSB           = 117 # symbol + addend, data4 LSB
        R_IA64_LTV64MSB           = 118 # symbol + addend, data8 MSB
        R_IA64_LTV64LSB           = 119 # symbol + addend, data8 LSB
        R_IA64_PCREL21BI          = 121 # @pcrel(sym+add), ptb, call
        R_IA64_PCREL22            = 122 # @pcrel(sym+add), imm22
        R_IA64_PCREL64I           = 123 # @pcrel(sym+add), imm64
        R_IA64_IPLTMSB            = 128 # dynamic reloc, imported PLT, MSB
        R_IA64_IPLTLSB            = 129 # dynamic reloc, imported PLT, LSB
        R_IA64_COPY               = 132 # dynamic reloc, data copy
        R_IA64_LTOFF22X           = 134 # LTOFF22, relaxable
        R_IA64_LDXMOV             = 135 # Use of LTOFF22X
        R_IA64_TPREL14            = 145 # @tprel(sym+add), add imm14
        R_IA64_TPREL22            = 146 # @tprel(sym+add), add imm22
        R_IA64_TPREL64I           = 147 # @tprel(sym+add), add imm64
        R_IA64_TPREL64MSB         = 150 # @tprel(sym+add), data8 MSB
        R_IA64_TPREL64LSB         = 151 # @tprel(sym+add), data8 LSB
        R_IA64_LTOFF_TPREL22      = 154 # @ltoff(@tprel(s+a)), add imm22
        R_IA64_DTPMOD64MSB        = 166 # @dtpmod(sym+add), data8 MSB
        R_IA64_DTPMOD64LSB        = 167 # @dtpmod(sym+add), data8 LSB
        R_IA64_LTOFF_DTPMOD22     = 170 # @ltoff(@dtpmod(s+a)), imm22
        R_IA64_DTPREL14           = 177 # @dtprel(sym+add), imm14
        R_IA64_DTPREL22           = 178 # @dtprel(sym+add), imm22
        R_IA64_DTPREL64I          = 179 # @dtprel(sym+add), imm64
        R_IA64_DTPREL32MSB        = 180 # @dtprel(sym+add), data4 MSB
        R_IA64_DTPREL32LSB        = 181 # @dtprel(sym+add), data4 LSB
        R_IA64_DTPREL64MSB        = 182 # @dtprel(sym+add), data8 MSB
        R_IA64_DTPREL64LSB        = 183 # @dtprel(sym+add), data8 LSB
        R_IA64_LTOFF_DTPREL22     = 186 # @ltoff(@dtprel(s+a)), imm22
        R_IA64_VMS_DIR8           = 1_879_048_192 # S + A
        R_IA64_VMS_DIR16LSB       = 1_879_048_193 # S + A
        R_IA64_VMS_CALL_SIGNATURE = 1_879_048_194 # :nodoc:
        R_IA64_VMS_EXECLET_FUNC   = 1_879_048_195 # :nodoc:
        R_IA64_VMS_EXECLET_DATA   = 1_879_048_196 # :nodoc:
        R_IA64_VMS_FIX8           = 1_879_048_197 # S + A
        R_IA64_VMS_FIX16          = 1_879_048_198 # S + A
        R_IA64_VMS_FIX32          = 1_879_048_199 # S + A
        R_IA64_VMS_FIX64          = 1_879_048_200 # S + A
        R_IA64_VMS_FIXFD          = 1_879_048_201 # :nodoc:
        R_IA64_VMS_ACC_LOAD       = 1_879_048_202 # ACC = S + A
        R_IA64_VMS_ACC_ADD        = 1_879_048_203 # ACC += S + A
        R_IA64_VMS_ACC_SUB        = 1_879_048_204 # ACC -= S + A
        R_IA64_VMS_ACC_MUL        = 1_879_048_205 # ACC *= S + A
        R_IA64_VMS_ACC_DIV        = 1_879_048_206 # ACC /= S + A
        R_IA64_VMS_ACC_AND        = 1_879_048_207 # ACC &= S + A
        R_IA64_VMS_ACC_IOR        = 1_879_048_208 # ACC |= S + A
        R_IA64_VMS_ACC_EOR        = 1_879_048_209 # ACC ^= S + A
        R_IA64_VMS_ACC_ASH        = 1_879_048_210 # ACC >>= S + A
        R_IA64_VMS_ACC_STO8       = 1_879_048_212 # ACC
        R_IA64_VMS_ACC_STO16LSH   = 1_879_048_213 # ACC
        R_IA64_VMS_ACC_STO32LSH   = 1_879_048_214 # ACC
        R_IA64_VMS_ACC_STO64LSH   = 1_879_048_215 # ACC
      end
    end
  end
end
