# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of IP2K.
      module IP2K
        R_IP2K_NONE      = 0 # :nodoc:
        R_IP2K_16        = 1 # :nodoc:
        R_IP2K_32        = 2 # :nodoc:
        R_IP2K_FR9       = 3 # :nodoc:
        R_IP2K_BANK      = 4 # :nodoc:
        R_IP2K_ADDR16CJP = 5 # :nodoc:
        R_IP2K_PAGE3     = 6 # :nodoc:
        R_IP2K_LO8DATA   = 7 # :nodoc:
        R_IP2K_HI8DATA   = 8 # :nodoc:
        R_IP2K_LO8INSN   = 9 # :nodoc:
        R_IP2K_HI8INSN   = 10 # :nodoc:
        R_IP2K_PC_SKIP   = 11 # :nodoc:
        R_IP2K_TEXT      = 12 # :nodoc:
        R_IP2K_FR_OFFSET = 13 # :nodoc:
        R_IP2K_EX8DATA   = 14 # :nodoc:
      end
    end
  end
end
