# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of IQ2000.
      module IQ2000
        R_IQ2000_NONE          = 0 # :nodoc:
        R_IQ2000_16            = 1 # :nodoc:
        R_IQ2000_32            = 2 # :nodoc:
        R_IQ2000_26            = 3 # :nodoc:
        R_IQ2000_PC16          = 4 # :nodoc:
        R_IQ2000_HI16          = 5 # :nodoc:
        R_IQ2000_LO16          = 6 # :nodoc:
        R_IQ2000_OFFSET_16     = 7 # :nodoc:
        R_IQ2000_OFFSET_21     = 8 # :nodoc:
        R_IQ2000_UHI16         = 9 # :nodoc:
        R_IQ2000_32_DEBUG      = 10 # :nodoc:
        R_IQ2000_GNU_VTINHERIT = 200 # :nodoc:
        R_IQ2000_GNU_VTENTRY   = 201 # :nodoc:
      end
    end
  end
end
