# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of KVX.
      module KVX
        R_KVX_NONE                = 0 # :nodoc:
        R_KVX_16                  = 1 # :nodoc:
        R_KVX_32                  = 2 # :nodoc:
        R_KVX_64                  = 3 # :nodoc:
        R_KVX_S16_PCREL           = 4 # :nodoc:
        R_KVX_PCREL17             = 5 # :nodoc:
        R_KVX_PCREL27             = 6 # :nodoc:
        R_KVX_32_PCREL            = 7 # :nodoc:
        R_KVX_S37_PCREL_LO10      = 8 # :nodoc:
        R_KVX_S37_PCREL_UP27      = 9 # :nodoc:
        R_KVX_S43_PCREL_LO10      = 10 # :nodoc:
        R_KVX_S43_PCREL_UP27      = 11 # :nodoc:
        R_KVX_S43_PCREL_EX6       = 12 # :nodoc:
        R_KVX_S64_PCREL_LO10      = 13 # :nodoc:
        R_KVX_S64_PCREL_UP27      = 14 # :nodoc:
        R_KVX_S64_PCREL_EX27      = 15 # :nodoc:
        R_KVX_64_PCREL            = 16 # :nodoc:
        R_KVX_S16                 = 17 # :nodoc:
        R_KVX_S32_LO5             = 18 # :nodoc:
        R_KVX_S32_UP27            = 19 # :nodoc:
        R_KVX_S37_LO10            = 20 # :nodoc:
        R_KVX_S37_UP27            = 21 # :nodoc:
        R_KVX_S37_GOTOFF_LO10     = 22 # :nodoc:
        R_KVX_S37_GOTOFF_UP27     = 23 # :nodoc:
        R_KVX_S43_GOTOFF_LO10     = 24 # :nodoc:
        R_KVX_S43_GOTOFF_UP27     = 25 # :nodoc:
        R_KVX_S43_GOTOFF_EX6      = 26 # :nodoc:
        R_KVX_32_GOTOFF           = 27 # :nodoc:
        R_KVX_64_GOTOFF           = 28 # :nodoc:
        R_KVX_32_GOT              = 29 # :nodoc:
        R_KVX_S37_GOT_LO10        = 30 # :nodoc:
        R_KVX_S37_GOT_UP27        = 31 # :nodoc:
        R_KVX_S43_GOT_LO10        = 32 # :nodoc:
        R_KVX_S43_GOT_UP27        = 33 # :nodoc:
        R_KVX_S43_GOT_EX6         = 34 # :nodoc:
        R_KVX_64_GOT              = 35 # :nodoc:
        R_KVX_GLOB_DAT            = 36 # :nodoc:
        R_KVX_COPY                = 37 # :nodoc:
        R_KVX_JMP_SLOT            = 38 # :nodoc:
        R_KVX_RELATIVE            = 39 # :nodoc:
        R_KVX_S43_LO10            = 40 # :nodoc:
        R_KVX_S43_UP27            = 41 # :nodoc:
        R_KVX_S43_EX6             = 42 # :nodoc:
        R_KVX_S64_LO10            = 43 # :nodoc:
        R_KVX_S64_UP27            = 44 # :nodoc:
        R_KVX_S64_EX27            = 45 # :nodoc:
        R_KVX_S37_GOTADDR_LO10    = 46 # :nodoc:
        R_KVX_S37_GOTADDR_UP27    = 47 # :nodoc:
        R_KVX_S43_GOTADDR_LO10    = 48 # :nodoc:
        R_KVX_S43_GOTADDR_UP27    = 49 # :nodoc:
        R_KVX_S43_GOTADDR_EX6     = 50 # :nodoc:
        R_KVX_S64_GOTADDR_LO10    = 51 # :nodoc:
        R_KVX_S64_GOTADDR_UP27    = 52 # :nodoc:
        R_KVX_S64_GOTADDR_EX27    = 53 # :nodoc:
        R_KVX_64_DTPMOD           = 54 # :nodoc:
        R_KVX_64_DTPOFF           = 55 # :nodoc:
        R_KVX_S37_TLS_DTPOFF_LO10 = 56 # :nodoc:
        R_KVX_S37_TLS_DTPOFF_UP27 = 57 # :nodoc:
        R_KVX_S43_TLS_DTPOFF_LO10 = 58 # :nodoc:
        R_KVX_S43_TLS_DTPOFF_UP27 = 59 # :nodoc:
        R_KVX_S43_TLS_DTPOFF_EX6  = 60 # :nodoc:
        R_KVX_S37_TLS_GD_LO10     = 61 # :nodoc:
        R_KVX_S37_TLS_GD_UP27     = 62 # :nodoc:
        R_KVX_S43_TLS_GD_LO10     = 63 # :nodoc:
        R_KVX_S43_TLS_GD_UP27     = 64 # :nodoc:
        R_KVX_S43_TLS_GD_EX6      = 65 # :nodoc:
        R_KVX_S37_TLS_LD_LO10     = 66 # :nodoc:
        R_KVX_S37_TLS_LD_UP27     = 67 # :nodoc:
        R_KVX_S43_TLS_LD_LO10     = 68 # :nodoc:
        R_KVX_S43_TLS_LD_UP27     = 69 # :nodoc:
        R_KVX_S43_TLS_LD_EX6      = 70 # :nodoc:
        R_KVX_64_TPOFF            = 71 # :nodoc:
        R_KVX_S37_TLS_IE_LO10     = 72 # :nodoc:
        R_KVX_S37_TLS_IE_UP27     = 73 # :nodoc:
        R_KVX_S43_TLS_IE_LO10     = 74 # :nodoc:
        R_KVX_S43_TLS_IE_UP27     = 75 # :nodoc:
        R_KVX_S43_TLS_IE_EX6      = 76 # :nodoc:
        R_KVX_S37_TLS_LE_LO10     = 77 # :nodoc:
        R_KVX_S37_TLS_LE_UP27     = 78 # :nodoc:
        R_KVX_S43_TLS_LE_LO10     = 79 # :nodoc:
        R_KVX_S43_TLS_LE_UP27     = 80 # :nodoc:
        R_KVX_S43_TLS_LE_EX6      = 81 # :nodoc:
        R_KVX_8                   = 82 # :nodoc:
      end
    end
  end
end
