# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of LM32.
      module LM32
        R_LM32_NONE          = 0 # :nodoc:
        R_LM32_8             = 1 # :nodoc:
        R_LM32_16            = 2 # :nodoc:
        R_LM32_32            = 3 # :nodoc:
        R_LM32_HI16          = 4 # :nodoc:
        R_LM32_LO16          = 5 # :nodoc:
        R_LM32_GPREL16       = 6 # :nodoc:
        R_LM32_CALL          = 7 # :nodoc:
        R_LM32_BRANCH        = 8 # :nodoc:
        R_LM32_GNU_VTINHERIT = 9 # :nodoc:
        R_LM32_GNU_VTENTRY   = 10 # :nodoc:
        R_LM32_16_GOT        = 11 # :nodoc:
        R_LM32_GOTOFF_HI16   = 12 # :nodoc:
        R_LM32_GOTOFF_LO16   = 13 # :nodoc:
        R_LM32_COPY          = 14 # :nodoc:
        R_LM32_GLOB_DAT      = 15 # :nodoc:
        R_LM32_JMP_SLOT      = 16 # :nodoc:
        R_LM32_RELATIVE      = 17 # :nodoc:
      end
    end
  end
end
