# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of M32C.
      module M32C
        R_M32C_NONE     = 0 # :nodoc:
        R_M32C_16       = 1 # :nodoc:
        R_M32C_24       = 2 # :nodoc:
        R_M32C_32       = 3 # :nodoc:
        R_M32C_8_PCREL  = 4 # :nodoc:
        R_M32C_16_PCREL = 5 # :nodoc:
        R_M32C_8        = 6 # :nodoc:
        R_M32C_LO16     = 7 # :nodoc:
        R_M32C_HI8      = 8 # :nodoc:
        R_M32C_HI16     = 9 # :nodoc:
        R_M32C_RL_JUMP  = 10 # :nodoc:
        R_M32C_RL_1ADDR = 11 # :nodoc:
        R_M32C_RL_2ADDR = 12 # :nodoc:
      end
    end
  end
end
