# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of M32R.
      module M32R
        R_M32R_NONE               = 0 # :nodoc:
        R_M32R_16                 = 1 # For backwards compatibility
        R_M32R_32                 = 2 # For backwards compatibility
        R_M32R_24                 = 3 # For backwards compatibility
        R_M32R_10_PCREL           = 4 # For backwards compatibility
        R_M32R_18_PCREL           = 5 # For backwards compatibility
        R_M32R_26_PCREL           = 6 # For backwards compatibility
        R_M32R_HI16_ULO           = 7 # For backwards compatibility
        R_M32R_HI16_SLO           = 8 # For backwards compatibility
        R_M32R_LO16               = 9 # For backwards compatibility
        R_M32R_SDA16              = 10 # For backwards compatibility
        R_M32R_GNU_VTINHERIT      = 11 # For backwards compatibility
        R_M32R_GNU_VTENTRY        = 12 # For backwards compatibility
        R_M32R_16_RELA            = 33 # :nodoc:
        R_M32R_32_RELA            = 34 # :nodoc:
        R_M32R_24_RELA            = 35 # :nodoc:
        R_M32R_10_PCREL_RELA      = 36 # :nodoc:
        R_M32R_18_PCREL_RELA      = 37 # :nodoc:
        R_M32R_26_PCREL_RELA      = 38 # :nodoc:
        R_M32R_HI16_ULO_RELA      = 39 # :nodoc:
        R_M32R_HI16_SLO_RELA      = 40 # :nodoc:
        R_M32R_LO16_RELA          = 41 # :nodoc:
        R_M32R_SDA16_RELA         = 42 # :nodoc:
        R_M32R_RELA_GNU_VTINHERIT = 43 # :nodoc:
        R_M32R_RELA_GNU_VTENTRY   = 44 # :nodoc:
        R_M32R_REL32              = 45 # :nodoc:
        R_M32R_GOT24              = 48 # :nodoc:
        R_M32R_26_PLTREL          = 49 # :nodoc:
        R_M32R_COPY               = 50 # :nodoc:
        R_M32R_GLOB_DAT           = 51 # :nodoc:
        R_M32R_JMP_SLOT           = 52 # :nodoc:
        R_M32R_RELATIVE           = 53 # :nodoc:
        R_M32R_GOTOFF             = 54 # :nodoc:
        R_M32R_GOTPC24            = 55 # :nodoc:
        R_M32R_GOT16_HI_ULO       = 56 # :nodoc:
        R_M32R_GOT16_HI_SLO       = 57 # :nodoc:
        R_M32R_GOT16_LO           = 58 # :nodoc:
        R_M32R_GOTPC_HI_ULO       = 59 # :nodoc:
        R_M32R_GOTPC_HI_SLO       = 60 # :nodoc:
        R_M32R_GOTPC_LO           = 61 # :nodoc:
        R_M32R_GOTOFF_HI_ULO      = 62 # :nodoc:
        R_M32R_GOTOFF_HI_SLO      = 63 # :nodoc:
        R_M32R_GOTOFF_LO          = 64 # :nodoc:
      end
    end
  end
end
