# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of M68HC11.
      module M68HC11
        R_M68HC11_NONE          = 0 # :nodoc:
        R_M68HC11_8             = 1 # :nodoc:
        R_M68HC11_HI8           = 2 # :nodoc:
        R_M68HC11_LO8           = 3 # :nodoc:
        R_M68HC11_PCREL_8       = 4 # :nodoc:
        R_M68HC11_16            = 5 # :nodoc:
        R_M68HC11_32            = 6 # :nodoc:
        R_M68HC11_3B            = 7 # :nodoc:
        R_M68HC11_PCREL_16      = 8 # :nodoc:
        R_M68HC11_GNU_VTINHERIT = 9 # :nodoc:
        R_M68HC11_GNU_VTENTRY   = 10 # :nodoc:
        R_M68HC11_24            = 11 # :nodoc:
        R_M68HC11_LO16          = 12 # :nodoc:
        R_M68HC11_PAGE          = 13 # :nodoc:
        R_M68HC12_16B           = 15 # :nodoc:
        R_M68HC12_PCREL_9       = 16 # :nodoc:
        R_M68HC12_PCREL_10      = 17 # :nodoc:
        R_M68HC12_HI8XG         = 18 # :nodoc:
        R_M68HC12_LO8XG         = 19 # :nodoc:
        R_M68HC11_RL_JUMP       = 20 # :nodoc:
        R_M68HC11_RL_GROUP      = 21 # :nodoc:
      end
    end
  end
end
