# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of M68K.
      module M68K
        R_68K_NONE          = 0 # No reloc
        R_68K_32            = 1 # Direct 32 bit
        R_68K_16            = 2 # Direct 16 bit
        R_68K_8             = 3 # Direct 8 bit
        R_68K_PC32          = 4 # PC relative 32 bit
        R_68K_PC16          = 5 # PC relative 16 bit
        R_68K_PC8           = 6 # PC relative 8 bit
        R_68K_GOT32         = 7 # 32 bit PC relative GOT entry
        R_68K_GOT16         = 8 # 16 bit PC relative GOT entry
        R_68K_GOT8          = 9 # 8 bit PC relative GOT entry
        R_68K_GOT32O        = 10 # 32 bit GOT offset
        R_68K_GOT16O        = 11 # 16 bit GOT offset
        R_68K_GOT8O         = 12 # 8 bit GOT offset
        R_68K_PLT32         = 13 # 32 bit PC relative PLT address
        R_68K_PLT16         = 14 # 16 bit PC relative PLT address
        R_68K_PLT8          = 15 # 8 bit PC relative PLT address
        R_68K_PLT32O        = 16 # 32 bit PLT offset
        R_68K_PLT16O        = 17 # 16 bit PLT offset
        R_68K_PLT8O         = 18 # 8 bit PLT offset
        R_68K_COPY          = 19 # Copy symbol at runtime
        R_68K_GLOB_DAT      = 20 # Create GOT entry
        R_68K_JMP_SLOT      = 21 # Create PLT entry
        R_68K_RELATIVE      = 22 # Adjust by program base
        R_68K_GNU_VTINHERIT = 23 # :nodoc:
        R_68K_GNU_VTENTRY   = 24 # :nodoc:
        R_68K_TLS_GD32      = 25 # :nodoc:
        R_68K_TLS_GD16      = 26 # :nodoc:
        R_68K_TLS_GD8       = 27 # :nodoc:
        R_68K_TLS_LDM32     = 28 # :nodoc:
        R_68K_TLS_LDM16     = 29 # :nodoc:
        R_68K_TLS_LDM8      = 30 # :nodoc:
        R_68K_TLS_LDO32     = 31 # :nodoc:
        R_68K_TLS_LDO16     = 32 # :nodoc:
        R_68K_TLS_LDO8      = 33 # :nodoc:
        R_68K_TLS_IE32      = 34 # :nodoc:
        R_68K_TLS_IE16      = 35 # :nodoc:
        R_68K_TLS_IE8       = 36 # :nodoc:
        R_68K_TLS_LE32      = 37 # :nodoc:
        R_68K_TLS_LE16      = 38 # :nodoc:
        R_68K_TLS_LE8       = 39 # :nodoc:
        R_68K_TLS_DTPMOD32  = 40 # :nodoc:
        R_68K_TLS_DTPREL32  = 41 # :nodoc:
        R_68K_TLS_TPREL32   = 42 # :nodoc:
      end
    end
  end
end
