# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MCORE.
      module MCORE
        R_MCORE_NONE              = 0 # :nodoc:
        R_MCORE_ADDR32            = 1 # :nodoc:
        R_MCORE_PCRELIMM8BY4      = 2 # :nodoc:
        R_MCORE_PCRELIMM11BY2     = 3 # :nodoc:
        R_MCORE_PCRELIMM4BY2      = 4 # :nodoc:
        R_MCORE_PCREL32           = 5 # :nodoc:
        R_MCORE_PCRELJSR_IMM11BY2 = 6 # :nodoc:
        R_MCORE_GNU_VTINHERIT     = 7 # :nodoc:
        R_MCORE_GNU_VTENTRY       = 8 # :nodoc:
        R_MCORE_RELATIVE          = 9 # :nodoc:
        R_MCORE_COPY              = 10 # :nodoc:
        R_MCORE_GLOB_DAT          = 11 # :nodoc:
        R_MCORE_JUMP_SLOT         = 12 # :nodoc:
      end
    end
  end
end
