# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MEP.
      module MEP
        R_MEP_NONE          = 0 # :nodoc:
        R_RELC              = 1 # :nodoc:
        R_MEP_8             = 2 # 7654 3210 U
        R_MEP_16            = 3 # fedc ba98 7654 3210 U
        R_MEP_32            = 4 # vuts rqpo nmlk jihg fedc ba98 7654 3210 U
        R_MEP_PCREL8A2      = 5 # ---- ---- 7654 321- S PC-REL
        R_MEP_PCREL12A2     = 6 # ---- ba98 7654 321- S PC-REL
        R_MEP_PCREL17A2     = 7 # ---- ---- ---- ---- gfed cba9 8765 4321 S PC-REL
        R_MEP_PCREL24A2     = 8 # ---- -765 4321 ---- nmlk jihg fedc ba98 S PC-REL
        R_MEP_PCABS24A2     = 9 # ---- -765 4321 ---- nmlk jihg fedc ba98 U
        R_MEP_LOW16         = 10 # ---- ---- ---- ---- fedc ba98 7654 3210 U no-overflow
        R_MEP_HI16U         = 11 # ---- ---- ---- ---- vuts rqpo nmlk jihg U no-overflow
        R_MEP_HI16S         = 12 # ---- ---- ---- ---- vuts rqpo nmlk jihg S no-overflow
        R_MEP_GPREL         = 13 # ---- ---- ---- ---- fedc ba98 7654 3210 S GP-REL
        R_MEP_TPREL         = 14 # ---- ---- ---- ---- fedc ba98 7654 3210 S TP-REL
        R_MEP_TPREL7        = 15 # ---- ---- -654 3210 U TP-REL
        R_MEP_TPREL7A2      = 16 # ---- ---- -654 321- U TP-REL
        R_MEP_TPREL7A4      = 17 # ---- ---- -654 32-- U TP-REL
        R_MEP_UIMM24        = 18 # ---- ---- 7654 3210 nmlk jihg fedc ba98 U
        R_MEP_ADDR24A4      = 19 # ---- ---- 7654 32-- nmlk jihg fedc ba98 U
        R_MEP_GNU_VTINHERIT = 20 # ---- ---- ---- ---- U no-overflow
        R_MEP_GNU_VTENTRY   = 21 # ---- ---- ---- ---- U no-overflow
      end
    end
  end
end
