# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of METAG.
      module METAG
        R_METAG_HIADDR16          = 0 # :nodoc:
        R_METAG_LOADDR16          = 1 # :nodoc:
        R_METAG_ADDR32            = 2 # :nodoc:
        R_METAG_NONE              = 3 # :nodoc:
        R_METAG_RELBRANCH         = 4 # :nodoc:
        R_METAG_GETSETOFF         = 5 # :nodoc:
        R_METAG_REG32OP1          = 6 # :nodoc:
        R_METAG_REG32OP2          = 7 # :nodoc:
        R_METAG_REG32OP3          = 8 # :nodoc:
        R_METAG_REG16OP1          = 9 # :nodoc:
        R_METAG_REG16OP2          = 10 # :nodoc:
        R_METAG_REG16OP3          = 11 # :nodoc:
        R_METAG_REG32OP4          = 12 # :nodoc:
        R_METAG_HIOG              = 13 # :nodoc:
        R_METAG_LOOG              = 14 # :nodoc:
        R_METAG_REL8              = 15 # :nodoc:
        R_METAG_REL16             = 16 # :nodoc:
        R_METAG_GNU_VTINHERIT     = 30 # :nodoc:
        R_METAG_GNU_VTENTRY       = 31 # :nodoc:
        R_METAG_HI16_GOTOFF       = 32 # :nodoc:
        R_METAG_LO16_GOTOFF       = 33 # :nodoc:
        R_METAG_GETSET_GOTOFF     = 34 # :nodoc:
        R_METAG_GETSET_GOT        = 35 # :nodoc:
        R_METAG_HI16_GOTPC        = 36 # :nodoc:
        R_METAG_LO16_GOTPC        = 37 # :nodoc:
        R_METAG_HI16_PLT          = 38 # :nodoc:
        R_METAG_LO16_PLT          = 39 # :nodoc:
        R_METAG_RELBRANCH_PLT     = 40 # :nodoc:
        R_METAG_GOTOFF            = 41 # :nodoc:
        R_METAG_PLT               = 42 # :nodoc:
        R_METAG_COPY              = 43 # :nodoc:
        R_METAG_JMP_SLOT          = 44 # :nodoc:
        R_METAG_RELATIVE          = 45 # :nodoc:
        R_METAG_GLOB_DAT          = 46 # :nodoc:
        R_METAG_TLS_GD            = 47 # :nodoc:
        R_METAG_TLS_LDM           = 48 # :nodoc:
        R_METAG_TLS_LDO_HI16      = 49 # :nodoc:
        R_METAG_TLS_LDO_LO16      = 50 # :nodoc:
        R_METAG_TLS_LDO           = 51 # :nodoc:
        R_METAG_TLS_IE            = 52 # :nodoc:
        R_METAG_TLS_IENONPIC      = 53 # :nodoc:
        R_METAG_TLS_IENONPIC_HI16 = 54 # :nodoc:
        R_METAG_TLS_IENONPIC_LO16 = 55 # :nodoc:
        R_METAG_TLS_TPOFF         = 56 # :nodoc:
        R_METAG_TLS_DTPMOD        = 57 # :nodoc:
        R_METAG_TLS_DTPOFF        = 58 # :nodoc:
        R_METAG_TLS_LE            = 59 # :nodoc:
        R_METAG_TLS_LE_HI16       = 60 # :nodoc:
        R_METAG_TLS_LE_LO16       = 61 # :nodoc:
      end
    end
  end
end
