# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MICROBLAZE.
      module MICROBLAZE
        R_MICROBLAZE_NONE          = 0 # :nodoc:
        R_MICROBLAZE_32            = 1 # :nodoc:
        R_MICROBLAZE_32_PCREL      = 2 # :nodoc:
        R_MICROBLAZE_64_PCREL      = 3 # :nodoc:
        R_MICROBLAZE_32_PCREL_LO   = 4 # :nodoc:
        R_MICROBLAZE_64            = 5 # :nodoc:
        R_MICROBLAZE_32_LO         = 6 # :nodoc:
        R_MICROBLAZE_SRO32         = 7 # :nodoc:
        R_MICROBLAZE_SRW32         = 8 # :nodoc:
        R_MICROBLAZE_64_NONE       = 9 # :nodoc:
        R_MICROBLAZE_32_SYM_OP_SYM = 10 # :nodoc:
        R_MICROBLAZE_GNU_VTINHERIT = 11 # :nodoc:
        R_MICROBLAZE_GNU_VTENTRY   = 12 # :nodoc:
        R_MICROBLAZE_GOTPC_64      = 13 # PC-relative GOT offset
        R_MICROBLAZE_GOT_64        = 14 # GOT entry offset
        R_MICROBLAZE_PLT_64        = 15 # PLT offset (PC-relative)
        R_MICROBLAZE_REL           = 16 # Adjust by program base
        R_MICROBLAZE_JUMP_SLOT     = 17 # Create PLT entry
        R_MICROBLAZE_GLOB_DAT      = 18 # Create GOT entry
        R_MICROBLAZE_GOTOFF_64     = 19 # Offset relative to GOT
        R_MICROBLAZE_GOTOFF_32     = 20 # Offset relative to GOT
        R_MICROBLAZE_COPY          = 21 # Runtime copy
        R_MICROBLAZE_TLS           = 22 # TLS Reloc
        R_MICROBLAZE_TLSGD         = 23 # TLS General Dynamic
        R_MICROBLAZE_TLSLD         = 24 # TLS Local Dynamic
        R_MICROBLAZE_TLSDTPMOD32   = 25 # TLS Module ID
        R_MICROBLAZE_TLSDTPREL32   = 26 # TLS Offset Within TLS Block
        R_MICROBLAZE_TLSDTPREL64   = 27 # TLS Offset Within TLS Block
        R_MICROBLAZE_TLSGOTTPREL32 = 28 # TLS Offset From Thread Pointer
        R_MICROBLAZE_TLSTPREL32    = 29 # TLS Offset From Thread Pointer
        R_MICROBLAZE_TEXTPCREL_64  = 30 # PC-relative TEXT offset
        R_MICROBLAZE_TEXTREL_64    = 31 # TEXT Entry offset 64-bit
        R_MICROBLAZE_TEXTREL_32_LO = 32 # TEXT Entry offset 32-bit
        R_MICROBLAZE_32_NONE       = 33 # :nodoc:
      end
    end
  end
end
