# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MIPS.
      module MIPS
        R_MIPS_NONE                 = 0 # :nodoc:
        R_MIPS_16                   = 1 # :nodoc:
        R_MIPS_32                   = 2 # In Elf 64: alias R_MIPS_ADD
        R_MIPS_REL32                = 3 # In Elf 64: alias R_MIPS_REL
        R_MIPS_26                   = 4 # :nodoc:
        R_MIPS_HI16                 = 5 # :nodoc:
        R_MIPS_LO16                 = 6 # :nodoc:
        R_MIPS_GPREL16              = 7 # In Elf 64: alias R_MIPS_GPREL
        R_MIPS_LITERAL              = 8 # :nodoc:
        R_MIPS_GOT16                = 9 # In Elf 64: alias R_MIPS_GOT
        R_MIPS_PC16                 = 10 # :nodoc:
        R_MIPS_CALL16               = 11 # In Elf 64: alias R_MIPS_CALL
        R_MIPS_GPREL32              = 12 # :nodoc:
        R_MIPS_UNUSED1              = 13 # :nodoc:
        R_MIPS_UNUSED2              = 14 # :nodoc:
        R_MIPS_UNUSED3              = 15 # :nodoc:
        R_MIPS_SHIFT5               = 16 # :nodoc:
        R_MIPS_SHIFT6               = 17 # :nodoc:
        R_MIPS_64                   = 18 # :nodoc:
        R_MIPS_GOT_DISP             = 19 # :nodoc:
        R_MIPS_GOT_PAGE             = 20 # :nodoc:
        R_MIPS_GOT_OFST             = 21 # :nodoc:
        R_MIPS_GOT_HI16             = 22 # :nodoc:
        R_MIPS_GOT_LO16             = 23 # :nodoc:
        R_MIPS_SUB                  = 24 # :nodoc:
        R_MIPS_INSERT_A             = 25 # :nodoc:
        R_MIPS_INSERT_B             = 26 # :nodoc:
        R_MIPS_DELETE               = 27 # :nodoc:
        R_MIPS_HIGHER               = 28 # :nodoc:
        R_MIPS_HIGHEST              = 29 # :nodoc:
        R_MIPS_CALL_HI16            = 30 # :nodoc:
        R_MIPS_CALL_LO16            = 31 # :nodoc:
        R_MIPS_SCN_DISP             = 32 # :nodoc:
        R_MIPS_REL16                = 33 # :nodoc:
        R_MIPS_ADD_IMMEDIATE        = 34 # :nodoc:
        R_MIPS_PJUMP                = 35 # :nodoc:
        R_MIPS_RELGOT               = 36 # :nodoc:
        R_MIPS_JALR                 = 37 # :nodoc:
        R_MIPS_TLS_DTPMOD32         = 38 # :nodoc:
        R_MIPS_TLS_DTPREL32         = 39 # :nodoc:
        R_MIPS_TLS_DTPMOD64         = 40 # :nodoc:
        R_MIPS_TLS_DTPREL64         = 41 # :nodoc:
        R_MIPS_TLS_GD               = 42 # :nodoc:
        R_MIPS_TLS_LDM              = 43 # :nodoc:
        R_MIPS_TLS_DTPREL_HI16      = 44 # :nodoc:
        R_MIPS_TLS_DTPREL_LO16      = 45 # :nodoc:
        R_MIPS_TLS_GOTTPREL         = 46 # :nodoc:
        R_MIPS_TLS_TPREL32          = 47 # :nodoc:
        R_MIPS_TLS_TPREL64          = 48 # :nodoc:
        R_MIPS_TLS_TPREL_HI16       = 49 # :nodoc:
        R_MIPS_TLS_TPREL_LO16       = 50 # :nodoc:
        R_MIPS_GLOB_DAT             = 51 # :nodoc:
        R_MIPS_PC21_S2              = 60 # :nodoc:
        R_MIPS_PC26_S2              = 61 # :nodoc:
        R_MIPS_PC18_S3              = 62 # :nodoc:
        R_MIPS_PC19_S2              = 63 # :nodoc:
        R_MIPS_PCHI16               = 64 # :nodoc:
        R_MIPS_PCLO16               = 65 # :nodoc:
        R_MIPS16_26                 = 100 # :nodoc:
        R_MIPS16_GPREL              = 101 # :nodoc:
        R_MIPS16_GOT16              = 102 # :nodoc:
        R_MIPS16_CALL16             = 103 # :nodoc:
        R_MIPS16_HI16               = 104 # :nodoc:
        R_MIPS16_LO16               = 105 # :nodoc:
        R_MIPS16_TLS_GD             = 106 # :nodoc:
        R_MIPS16_TLS_LDM            = 107 # :nodoc:
        R_MIPS16_TLS_DTPREL_HI16    = 108 # :nodoc:
        R_MIPS16_TLS_DTPREL_LO16    = 109 # :nodoc:
        R_MIPS16_TLS_GOTTPREL       = 110 # :nodoc:
        R_MIPS16_TLS_TPREL_HI16     = 111 # :nodoc:
        R_MIPS16_TLS_TPREL_LO16     = 112 # :nodoc:
        R_MIPS16_PC16_S1            = 113 # :nodoc:
        R_MIPS_COPY                 = 126 # :nodoc:
        R_MIPS_JUMP_SLOT            = 127 # :nodoc:
        R_MICROMIPS_26_S1           = 133 # :nodoc:
        R_MICROMIPS_HI16            = 134 # :nodoc:
        R_MICROMIPS_LO16            = 135 # :nodoc:
        R_MICROMIPS_GPREL16         = 136 # :nodoc:
        R_MICROMIPS_LITERAL         = 137 # :nodoc:
        R_MICROMIPS_GOT16           = 138 # :nodoc:
        R_MICROMIPS_PC7_S1          = 139 # :nodoc:
        R_MICROMIPS_PC10_S1         = 140 # :nodoc:
        R_MICROMIPS_PC16_S1         = 141 # :nodoc:
        R_MICROMIPS_CALL16          = 142 # :nodoc:
        R_MICROMIPS_GOT_DISP        = 145 # :nodoc:
        R_MICROMIPS_GOT_PAGE        = 146 # :nodoc:
        R_MICROMIPS_GOT_OFST        = 147 # :nodoc:
        R_MICROMIPS_GOT_HI16        = 148 # :nodoc:
        R_MICROMIPS_GOT_LO16        = 149 # :nodoc:
        R_MICROMIPS_SUB             = 150 # :nodoc:
        R_MICROMIPS_HIGHER          = 151 # :nodoc:
        R_MICROMIPS_HIGHEST         = 152 # :nodoc:
        R_MICROMIPS_CALL_HI16       = 153 # :nodoc:
        R_MICROMIPS_CALL_LO16       = 154 # :nodoc:
        R_MICROMIPS_SCN_DISP        = 155 # :nodoc:
        R_MICROMIPS_JALR            = 156 # :nodoc:
        R_MICROMIPS_HI0_LO16        = 157 # :nodoc:
        R_MICROMIPS_TLS_GD          = 162 # :nodoc:
        R_MICROMIPS_TLS_LDM         = 163 # :nodoc:
        R_MICROMIPS_TLS_DTPREL_HI16 = 164 # :nodoc:
        R_MICROMIPS_TLS_DTPREL_LO16 = 165 # :nodoc:
        R_MICROMIPS_TLS_GOTTPREL    = 166 # :nodoc:
        R_MICROMIPS_TLS_TPREL_HI16  = 169 # :nodoc:
        R_MICROMIPS_TLS_TPREL_LO16  = 170 # :nodoc:
        R_MICROMIPS_GPREL7_S2       = 172 # :nodoc:
        R_MICROMIPS_PC23_S2         = 173 # :nodoc:
        R_MIPS_PC32                 = 248 # :nodoc:
        R_MIPS_EH                   = 249 # :nodoc:
        R_MIPS_GNU_REL16_S2         = 250 # :nodoc:
        R_MIPS_GNU_VTINHERIT        = 253 # :nodoc:
        R_MIPS_GNU_VTENTRY          = 254 # :nodoc:
      end
    end
  end
end
