# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MMIX.
      module MMIX
        R_MMIX_NONE             = 0 # :nodoc:
        R_MMIX_8                = 1 # :nodoc:
        R_MMIX_16               = 2 # :nodoc:
        R_MMIX_24               = 3 # :nodoc:
        R_MMIX_32               = 4 # :nodoc:
        R_MMIX_64               = 5 # :nodoc:
        R_MMIX_PC_8             = 6 # :nodoc:
        R_MMIX_PC_16            = 7 # :nodoc:
        R_MMIX_PC_24            = 8 # :nodoc:
        R_MMIX_PC_32            = 9 # :nodoc:
        R_MMIX_PC_64            = 10 # :nodoc:
        R_MMIX_GNU_VTINHERIT    = 11 # :nodoc:
        R_MMIX_GNU_VTENTRY      = 12 # :nodoc:
        R_MMIX_GETA             = 13 # :nodoc:
        R_MMIX_GETA_1           = 14 # :nodoc:
        R_MMIX_GETA_2           = 15 # :nodoc:
        R_MMIX_GETA_3           = 16 # :nodoc:
        R_MMIX_CBRANCH          = 17 # :nodoc:
        R_MMIX_CBRANCH_J        = 18 # :nodoc:
        R_MMIX_CBRANCH_1        = 19 # :nodoc:
        R_MMIX_CBRANCH_2        = 20 # :nodoc:
        R_MMIX_CBRANCH_3        = 21 # :nodoc:
        R_MMIX_PUSHJ            = 22 # :nodoc:
        R_MMIX_PUSHJ_1          = 23 # :nodoc:
        R_MMIX_PUSHJ_2          = 24 # :nodoc:
        R_MMIX_PUSHJ_3          = 25 # :nodoc:
        R_MMIX_JMP              = 26 # :nodoc:
        R_MMIX_JMP_1            = 27 # :nodoc:
        R_MMIX_JMP_2            = 28 # :nodoc:
        R_MMIX_JMP_3            = 29 # :nodoc:
        R_MMIX_ADDR19           = 30 # :nodoc:
        R_MMIX_ADDR27           = 31 # :nodoc:
        R_MMIX_REG_OR_BYTE      = 32 # :nodoc:
        R_MMIX_REG              = 33 # :nodoc:
        R_MMIX_BASE_PLUS_OFFSET = 34 # :nodoc:
        R_MMIX_LOCAL            = 35 # :nodoc:
        R_MMIX_PUSHJ_STUBBABLE  = 36 # :nodoc:
      end
    end
  end
end
