# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MN10200.
      module MN10200
        R_MN10200_NONE    = 0 # :nodoc:
        R_MN10200_32      = 1 # :nodoc:
        R_MN10200_16      = 2 # :nodoc:
        R_MN10200_8       = 3 # :nodoc:
        R_MN10200_24      = 4 # :nodoc:
        R_MN10200_PCREL8  = 5 # :nodoc:
        R_MN10200_PCREL16 = 6 # :nodoc:
        R_MN10200_PCREL24 = 7 # :nodoc:
      end
    end
  end
end
