# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MN10300.
      module MN10300
        R_MN10300_NONE          = 0 # :nodoc:
        R_MN10300_32            = 1 # :nodoc:
        R_MN10300_16            = 2 # :nodoc:
        R_MN10300_8             = 3 # :nodoc:
        R_MN10300_PCREL32       = 4 # :nodoc:
        R_MN10300_PCREL16       = 5 # :nodoc:
        R_MN10300_PCREL8        = 6 # :nodoc:
        R_MN10300_GNU_VTINHERIT = 7 # :nodoc:
        R_MN10300_GNU_VTENTRY   = 8 # :nodoc:
        R_MN10300_24            = 9 # :nodoc:
        R_MN10300_GOTPC32       = 10 # :nodoc:
        R_MN10300_GOTPC16       = 11 # :nodoc:
        R_MN10300_GOTOFF32      = 12 # :nodoc:
        R_MN10300_GOTOFF24      = 13 # :nodoc:
        R_MN10300_GOTOFF16      = 14 # :nodoc:
        R_MN10300_PLT32         = 15 # :nodoc:
        R_MN10300_PLT16         = 16 # :nodoc:
        R_MN10300_GOT32         = 17 # :nodoc:
        R_MN10300_GOT24         = 18 # :nodoc:
        R_MN10300_GOT16         = 19 # :nodoc:
        R_MN10300_COPY          = 20 # :nodoc:
        R_MN10300_GLOB_DAT      = 21 # :nodoc:
        R_MN10300_JMP_SLOT      = 22 # :nodoc:
        R_MN10300_RELATIVE      = 23 # :nodoc:
        R_MN10300_TLS_GD        = 24 # :nodoc:
        R_MN10300_TLS_LD        = 25 # :nodoc:
        R_MN10300_TLS_LDO       = 26 # :nodoc:
        R_MN10300_TLS_GOTIE     = 27 # :nodoc:
        R_MN10300_TLS_IE        = 28 # :nodoc:
        R_MN10300_TLS_LE        = 29 # :nodoc:
        R_MN10300_TLS_DTPMOD    = 30 # :nodoc:
        R_MN10300_TLS_DTPOFF    = 31 # :nodoc:
        R_MN10300_TLS_TPOFF     = 32 # :nodoc:
        R_MN10300_SYM_DIFF      = 33 # :nodoc:
        R_MN10300_ALIGN         = 34 # :nodoc:
      end
    end
  end
end
