# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MOXIE.
      module MOXIE
        R_MOXIE_NONE    = 0 # :nodoc:
        R_MOXIE_32      = 1 # :nodoc:
        R_MOXIE_PCREL10 = 2 # :nodoc:
      end
    end
  end
end
