# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MSP430.
      module MSP430
        R_MSP430_NONE            = 0 # :nodoc:
        R_MSP430_32              = 1 # :nodoc:
        R_MSP430_10_PCREL        = 2 # :nodoc:
        R_MSP430_16              = 3 # :nodoc:
        R_MSP430_16_PCREL        = 4 # :nodoc:
        R_MSP430_16_BYTE         = 5 # :nodoc:
        R_MSP430_16_PCREL_BYTE   = 6 # :nodoc:
        R_MSP430_2X_PCREL        = 7 # :nodoc:
        R_MSP430_RL_PCREL        = 8 # :nodoc:
        R_MSP430_8               = 9 # :nodoc:
        R_MSP430_SYM_DIFF        = 10 # :nodoc:
        R_MSP430_GNU_SET_ULEB128 = 11 # GNU only
        R_MSP430_GNU_SUB_ULEB128 = 12 # GNU only
      end
    end
  end
end
