# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MSP430X.
      module MSP430X
        R_MSP430_ABS32            = 1 # aka R_MSP430_32
        R_MSP430_ABS16            = 2 # aka R_MSP430_16
        R_MSP430_ABS8             = 3 # :nodoc:
        R_MSP430_PCR16            = 4 # aka R_MSP430_16_PCREL
        R_MSP430X_PCR20_EXT_SRC   = 5 # :nodoc:
        R_MSP430X_PCR20_EXT_DST   = 6 # :nodoc:
        R_MSP430X_PCR20_EXT_ODST  = 7 # :nodoc:
        R_MSP430X_ABS20_EXT_SRC   = 8 # :nodoc:
        R_MSP430X_ABS20_EXT_DST   = 9 # :nodoc:
        R_MSP430X_ABS20_EXT_ODST  = 10 # :nodoc:
        R_MSP430X_ABS20_ADR_SRC   = 11 # :nodoc:
        R_MSP430X_ABS20_ADR_DST   = 12 # :nodoc:
        R_MSP430X_PCR16           = 13 # Like R_MSP430_PCR16 but with overflow checking
        R_MSP430X_PCR20_CALL      = 14 # :nodoc:
        R_MSP430X_ABS16           = 15 # Like R_MSP430_ABS16 but with overflow checking
        R_MSP430_ABS_HI16         = 16 # :nodoc:
        R_MSP430_PREL31           = 17 # :nodoc:
        R_MSP430_EHTYPE           = 18 # Mentioned in ABI
        R_MSP430X_10_PCREL        = 19 # Red Hat invention. Used for Jump instructions
        R_MSP430X_2X_PCREL        = 20 # Red Hat invention. Used for relaxing jumps
        R_MSP430X_SYM_DIFF        = 21 # Red Hat invention. Used for relaxing debug info
        R_MSP430X_GNU_SET_ULEB128 = 22 # GNU only
        R_MSP430X_GNU_SUB_ULEB128 = 23 # GNU only
      end
    end
  end
end
