# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of MT.
      module MT
        R_MT_NONE     = 0 # :nodoc:
        R_MT_16       = 1 # :nodoc:
        R_MT_32       = 2 # :nodoc:
        R_MT_32_PCREL = 3 # :nodoc:
        R_MT_PC16     = 4 # :nodoc:
        R_MT_HI16     = 5 # :nodoc:
        R_MT_LO16     = 6 # :nodoc:
      end
    end
  end
end
