# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of NFP.
      module NFP
        R_NFP_NOTYPE         = 0 # :nodoc:
        R_NFP_W32LE          = 1 # :nodoc:
        R_NFP_SRC8_A         = 2 # :nodoc:
        R_NFP_SRC8_B         = 3 # :nodoc:
        R_NFP_IMMED8_I       = 4 # :nodoc:
        R_NFP_SC             = 5 # :nodoc:
        R_NFP_IMMED_LO16_I_A = 6 # :nodoc:
        R_NFP_IMMED_LO16_I_B = 7 # :nodoc:
        R_NFP_SRC7_B         = 8 # :nodoc:
        R_NFP_SRC7_A         = 9 # :nodoc:
        R_NFP_SRC8_I_B       = 10 # :nodoc:
        R_NFP_SRC8_I_A       = 11 # :nodoc:
        R_NFP_IMMED_HI16_I_A = 12 # :nodoc:
        R_NFP_IMMED_HI16_I_B = 13 # :nodoc:
        R_NFP_W64LE          = 14 # :nodoc:
        R_NFP_SH_INFO        = 15 # :nodoc:
        R_NFP_W32BE          = 16 # :nodoc:
        R_NFP_W64BE          = 17 # :nodoc:
        R_NFP_W32_29_24      = 18 # :nodoc:
        R_NFP_W32LE_AND      = 19 # :nodoc:
        R_NFP_W32BE_AND      = 20 # :nodoc:
        R_NFP_W32LE_OR       = 21 # :nodoc:
        R_NFP_W32BE_OR       = 22 # :nodoc:
        R_NFP_W64LE_AND      = 23 # :nodoc:
        R_NFP_W64BE_AND      = 24 # :nodoc:
        R_NFP_W64LE_OR       = 25 # :nodoc:
        R_NFP_W64BE_OR       = 26 # :nodoc:
      end
    end
  end
end
