# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of NFP3200.
      module NFP3200
        R_NFP3200_NOTYPE         = 0 # :nodoc:
        R_NFP3200_W32LE          = 1 # :nodoc:
        R_NFP3200_SRC8_A         = 2 # :nodoc:
        R_NFP3200_SRC8_B         = 3 # :nodoc:
        R_NFP3200_IMMED8_I       = 4 # :nodoc:
        R_NFP3200_SC             = 5 # :nodoc:
        R_NFP3200_IMMED_LO16_I_A = 6 # :nodoc:
        R_NFP3200_IMMED_LO16_I_B = 7 # :nodoc:
        R_NFP3200_SRC7_B         = 8 # :nodoc:
        R_NFP3200_SRC7_A         = 9 # :nodoc:
        R_NFP3200_SRC8_I_B       = 10 # :nodoc:
        R_NFP3200_SRC8_I_A       = 11 # :nodoc:
        R_NFP3200_IMMED_HI16_I_A = 12 # :nodoc:
        R_NFP3200_IMMED_HI16_I_B = 13 # :nodoc:
        R_NFP3200_RSVD_0         = 14 # :nodoc:
        R_NFP3200_RSVD_1         = 15 # :nodoc:
        R_NFP3200_RSVD_2         = 16 # :nodoc:
        R_NFP3200_RSVD_3         = 17 # :nodoc:
        R_NFP3200_RSVD_4         = 18 # :nodoc:
        R_NFP3200_RSVD_5         = 19 # :nodoc:
        R_NFP3200_RSVD_6         = 20 # :nodoc:
        R_NFP3200_W64LE          = 21 # :nodoc:
        R_NFP3200_W32BE          = 22 # :nodoc:
        R_NFP3200_W64BE          = 23 # :nodoc:
        R_NFP3200_W32LE_AND      = 24 # :nodoc:
        R_NFP3200_W32BE_AND      = 25 # :nodoc:
        R_NFP3200_W32LE_OR       = 26 # :nodoc:
        R_NFP3200_W32BE_OR       = 27 # :nodoc:
        R_NFP3200_W64LE_AND      = 28 # :nodoc:
        R_NFP3200_W64BE_AND      = 29 # :nodoc:
        R_NFP3200_W64LE_OR       = 30 # :nodoc:
        R_NFP3200_W64BE_OR       = 31 # :nodoc:
      end
    end
  end
end
