# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of NIOS2.
      module NIOS2
        R_NIOS2_NONE            = 0 # :nodoc:
        R_NIOS2_S16             = 1 # :nodoc:
        R_NIOS2_U16             = 2 # :nodoc:
        R_NIOS2_PCREL16         = 3 # :nodoc:
        R_NIOS2_CALL26          = 4 # :nodoc:
        R_NIOS2_IMM5            = 5 # :nodoc:
        R_NIOS2_CACHE_OPX       = 6 # :nodoc:
        R_NIOS2_IMM6            = 7 # :nodoc:
        R_NIOS2_IMM8            = 8 # :nodoc:
        R_NIOS2_HI16            = 9 # :nodoc:
        R_NIOS2_LO16            = 10 # :nodoc:
        R_NIOS2_HIADJ16         = 11 # :nodoc:
        R_NIOS2_BFD_RELOC_32    = 12 # :nodoc:
        R_NIOS2_BFD_RELOC_16    = 13 # :nodoc:
        R_NIOS2_BFD_RELOC_8     = 14 # :nodoc:
        R_NIOS2_GPREL           = 15 # :nodoc:
        R_NIOS2_GNU_VTINHERIT   = 16 # :nodoc:
        R_NIOS2_GNU_VTENTRY     = 17 # :nodoc:
        R_NIOS2_UJMP            = 18 # :nodoc:
        R_NIOS2_CJMP            = 19 # :nodoc:
        R_NIOS2_CALLR           = 20 # :nodoc:
        R_NIOS2_ALIGN           = 21 # :nodoc:
        R_NIOS2_GOT16           = 22 # :nodoc:
        R_NIOS2_CALL16          = 23 # :nodoc:
        R_NIOS2_GOTOFF_LO       = 24 # :nodoc:
        R_NIOS2_GOTOFF_HA       = 25 # :nodoc:
        R_NIOS2_PCREL_LO        = 26 # :nodoc:
        R_NIOS2_PCREL_HA        = 27 # :nodoc:
        R_NIOS2_TLS_GD16        = 28 # :nodoc:
        R_NIOS2_TLS_LDM16       = 29 # :nodoc:
        R_NIOS2_TLS_LDO16       = 30 # :nodoc:
        R_NIOS2_TLS_IE16        = 31 # :nodoc:
        R_NIOS2_TLS_LE16        = 32 # :nodoc:
        R_NIOS2_TLS_DTPMOD      = 33 # :nodoc:
        R_NIOS2_TLS_DTPREL      = 34 # :nodoc:
        R_NIOS2_TLS_TPREL       = 35 # :nodoc:
        R_NIOS2_COPY            = 36 # :nodoc:
        R_NIOS2_GLOB_DAT        = 37 # :nodoc:
        R_NIOS2_JUMP_SLOT       = 38 # :nodoc:
        R_NIOS2_RELATIVE        = 39 # :nodoc:
        R_NIOS2_GOTOFF          = 40 # :nodoc:
        R_NIOS2_CALL26_NOAT     = 41 # :nodoc:
        R_NIOS2_GOT_LO          = 42 # :nodoc:
        R_NIOS2_GOT_HA          = 43 # :nodoc:
        R_NIOS2_CALL_LO         = 44 # :nodoc:
        R_NIOS2_CALL_HA         = 45 # :nodoc:
        R_NIOS2_R2_S12          = 64 # :nodoc:
        R_NIOS2_R2_I10_1_PCREL  = 65 # :nodoc:
        R_NIOS2_R2_T1I7_1_PCREL = 66 # :nodoc:
        R_NIOS2_R2_T1I7_2       = 67 # :nodoc:
        R_NIOS2_R2_T2I4         = 68 # :nodoc:
        R_NIOS2_R2_T2I4_1       = 69 # :nodoc:
        R_NIOS2_R2_T2I4_2       = 70 # :nodoc:
        R_NIOS2_R2_X1I7_2       = 71 # :nodoc:
        R_NIOS2_R2_X2L5         = 72 # :nodoc:
        R_NIOS2_R2_F1I5_2       = 73 # :nodoc:
        R_NIOS2_R2_L5I4X1       = 74 # :nodoc:
        R_NIOS2_R2_T1X1I6       = 75 # :nodoc:
        R_NIOS2_R2_T1X1I6_2     = 76 # :nodoc:
        R_NIOS2_ILLEGAL         = 77 # :nodoc:
      end
    end
  end
end
