# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of OR1K.
      module OR1K
        R_OR1K_NONE          = 0 # :nodoc:
        R_OR1K_32            = 1 # :nodoc:
        R_OR1K_16            = 2 # :nodoc:
        R_OR1K_8             = 3 # :nodoc:
        R_OR1K_LO_16_IN_INSN = 4 # :nodoc:
        R_OR1K_HI_16_IN_INSN = 5 # :nodoc:
        R_OR1K_INSN_REL_26   = 6 # :nodoc:
        R_OR1K_GNU_VTENTRY   = 7 # :nodoc:
        R_OR1K_GNU_VTINHERIT = 8 # :nodoc:
        R_OR1K_32_PCREL      = 9 # :nodoc:
        R_OR1K_16_PCREL      = 10 # :nodoc:
        R_OR1K_8_PCREL       = 11 # :nodoc:
        R_OR1K_GOTPC_HI16    = 12 # :nodoc:
        R_OR1K_GOTPC_LO16    = 13 # :nodoc:
        R_OR1K_GOT16         = 14 # :nodoc:
        R_OR1K_PLT26         = 15 # :nodoc:
        R_OR1K_GOTOFF_HI16   = 16 # :nodoc:
        R_OR1K_GOTOFF_LO16   = 17 # :nodoc:
        R_OR1K_COPY          = 18 # :nodoc:
        R_OR1K_GLOB_DAT      = 19 # :nodoc:
        R_OR1K_JMP_SLOT      = 20 # :nodoc:
        R_OR1K_RELATIVE      = 21 # :nodoc:
        R_OR1K_TLS_GD_HI16   = 22 # :nodoc:
        R_OR1K_TLS_GD_LO16   = 23 # :nodoc:
        R_OR1K_TLS_LDM_HI16  = 24 # :nodoc:
        R_OR1K_TLS_LDM_LO16  = 25 # :nodoc:
        R_OR1K_TLS_LDO_HI16  = 26 # :nodoc:
        R_OR1K_TLS_LDO_LO16  = 27 # :nodoc:
        R_OR1K_TLS_IE_HI16   = 28 # :nodoc:
        R_OR1K_TLS_IE_LO16   = 29 # :nodoc:
        R_OR1K_TLS_LE_HI16   = 30 # :nodoc:
        R_OR1K_TLS_LE_LO16   = 31 # :nodoc:
        R_OR1K_TLS_TPOFF     = 32 # :nodoc:
        R_OR1K_TLS_DTPOFF    = 33 # :nodoc:
        R_OR1K_TLS_DTPMOD    = 34 # :nodoc:
        R_OR1K_AHI16         = 35 # :nodoc:
        R_OR1K_GOTOFF_AHI16  = 36 # :nodoc:
        R_OR1K_TLS_IE_AHI16  = 37 # :nodoc:
        R_OR1K_TLS_LE_AHI16  = 38 # :nodoc:
        R_OR1K_SLO16         = 39 # :nodoc:
        R_OR1K_GOTOFF_SLO16  = 40 # :nodoc:
        R_OR1K_TLS_LE_SLO16  = 41 # :nodoc:
        R_OR1K_PCREL_PG21    = 42 # :nodoc:
        R_OR1K_GOT_PG21      = 43 # :nodoc:
        R_OR1K_TLS_GD_PG21   = 44 # :nodoc:
        R_OR1K_TLS_LDM_PG21  = 45 # :nodoc:
        R_OR1K_TLS_IE_PG21   = 46 # :nodoc:
        R_OR1K_LO13          = 47 # :nodoc:
        R_OR1K_GOT_LO13      = 48 # :nodoc:
        R_OR1K_TLS_GD_LO13   = 49 # :nodoc:
        R_OR1K_TLS_LDM_LO13  = 50 # :nodoc:
        R_OR1K_TLS_IE_LO13   = 51 # :nodoc:
        R_OR1K_SLO13         = 52 # :nodoc:
        R_OR1K_PLTA26        = 53 # :nodoc:
        R_OR1K_GOT_AHI16     = 54 # :nodoc:
      end
    end
  end
end
