# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of PJ.
      module PJ
        R_PJ_NONE          = 0 # :nodoc:
        R_PJ_DATA_DIR32    = 1 # :nodoc:
        R_PJ_CODE_REL32    = 2 # :nodoc:
        R_PJ_CODE_REL16    = 3 # :nodoc:
        R_PJ_CODE_DIR32    = 6 # :nodoc:
        R_PJ_CODE_DIR16    = 7 # :nodoc:
        R_PJ_CODE_LO16     = 13 # :nodoc:
        R_PJ_CODE_HI16     = 14 # :nodoc:
        R_PJ_GNU_VTINHERIT = 15 # :nodoc:
        R_PJ_GNU_VTENTRY   = 16 # :nodoc:
      end
    end
  end
end
