# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of PPC.
      module PPC
        R_PPC_NONE             = 0 # :nodoc:
        R_PPC_ADDR32           = 1 # :nodoc:
        R_PPC_ADDR24           = 2 # :nodoc:
        R_PPC_ADDR16           = 3 # :nodoc:
        R_PPC_ADDR16_LO        = 4 # :nodoc:
        R_PPC_ADDR16_HI        = 5 # :nodoc:
        R_PPC_ADDR16_HA        = 6 # :nodoc:
        R_PPC_ADDR14           = 7 # :nodoc:
        R_PPC_ADDR14_BRTAKEN   = 8 # :nodoc:
        R_PPC_ADDR14_BRNTAKEN  = 9 # :nodoc:
        R_PPC_REL24            = 10 # :nodoc:
        R_PPC_REL14            = 11 # :nodoc:
        R_PPC_REL14_BRTAKEN    = 12 # :nodoc:
        R_PPC_REL14_BRNTAKEN   = 13 # :nodoc:
        R_PPC_GOT16            = 14 # :nodoc:
        R_PPC_GOT16_LO         = 15 # :nodoc:
        R_PPC_GOT16_HI         = 16 # :nodoc:
        R_PPC_GOT16_HA         = 17 # :nodoc:
        R_PPC_PLTREL24         = 18 # :nodoc:
        R_PPC_COPY             = 19 # :nodoc:
        R_PPC_GLOB_DAT         = 20 # :nodoc:
        R_PPC_JMP_SLOT         = 21 # :nodoc:
        R_PPC_RELATIVE         = 22 # :nodoc:
        R_PPC_LOCAL24PC        = 23 # :nodoc:
        R_PPC_UADDR32          = 24 # :nodoc:
        R_PPC_UADDR16          = 25 # :nodoc:
        R_PPC_REL32            = 26 # :nodoc:
        R_PPC_PLT32            = 27 # :nodoc:
        R_PPC_PLTREL32         = 28 # :nodoc:
        R_PPC_PLT16_LO         = 29 # :nodoc:
        R_PPC_PLT16_HI         = 30 # :nodoc:
        R_PPC_PLT16_HA         = 31 # :nodoc:
        R_PPC_SDAREL16         = 32 # :nodoc:
        R_PPC_SECTOFF          = 33 # :nodoc:
        R_PPC_SECTOFF_LO       = 34 # :nodoc:
        R_PPC_SECTOFF_HI       = 35 # :nodoc:
        R_PPC_SECTOFF_HA       = 36 # :nodoc:
        R_PPC_ADDR30           = 37 # :nodoc:
        R_PPC_RELAX            = 48 # :nodoc:
        R_PPC_RELAX_PLT        = 49 # :nodoc:
        R_PPC_RELAX_PLTREL24   = 50 # :nodoc:
        R_PPC_16DX_HA          = 51 # :nodoc:
        R_PPC_TLS              = 67 # :nodoc:
        R_PPC_DTPMOD32         = 68 # :nodoc:
        R_PPC_TPREL16          = 69 # :nodoc:
        R_PPC_TPREL16_LO       = 70 # :nodoc:
        R_PPC_TPREL16_HI       = 71 # :nodoc:
        R_PPC_TPREL16_HA       = 72 # :nodoc:
        R_PPC_TPREL32          = 73 # :nodoc:
        R_PPC_DTPREL16         = 74 # :nodoc:
        R_PPC_DTPREL16_LO      = 75 # :nodoc:
        R_PPC_DTPREL16_HI      = 76 # :nodoc:
        R_PPC_DTPREL16_HA      = 77 # :nodoc:
        R_PPC_DTPREL32         = 78 # :nodoc:
        R_PPC_GOT_TLSGD16      = 79 # :nodoc:
        R_PPC_GOT_TLSGD16_LO   = 80 # :nodoc:
        R_PPC_GOT_TLSGD16_HI   = 81 # :nodoc:
        R_PPC_GOT_TLSGD16_HA   = 82 # :nodoc:
        R_PPC_GOT_TLSLD16      = 83 # :nodoc:
        R_PPC_GOT_TLSLD16_LO   = 84 # :nodoc:
        R_PPC_GOT_TLSLD16_HI   = 85 # :nodoc:
        R_PPC_GOT_TLSLD16_HA   = 86 # :nodoc:
        R_PPC_GOT_TPREL16      = 87 # :nodoc:
        R_PPC_GOT_TPREL16_LO   = 88 # :nodoc:
        R_PPC_GOT_TPREL16_HI   = 89 # :nodoc:
        R_PPC_GOT_TPREL16_HA   = 90 # :nodoc:
        R_PPC_GOT_DTPREL16     = 91 # :nodoc:
        R_PPC_GOT_DTPREL16_LO  = 92 # :nodoc:
        R_PPC_GOT_DTPREL16_HI  = 93 # :nodoc:
        R_PPC_GOT_DTPREL16_HA  = 94 # :nodoc:
        R_PPC_TLSGD            = 95 # :nodoc:
        R_PPC_TLSLD            = 96 # :nodoc:
        R_PPC_EMB_NADDR32      = 101 # :nodoc:
        R_PPC_EMB_NADDR16      = 102 # :nodoc:
        R_PPC_EMB_NADDR16_LO   = 103 # :nodoc:
        R_PPC_EMB_NADDR16_HI   = 104 # :nodoc:
        R_PPC_EMB_NADDR16_HA   = 105 # :nodoc:
        R_PPC_EMB_SDAI16       = 106 # :nodoc:
        R_PPC_EMB_SDA2I16      = 107 # :nodoc:
        R_PPC_EMB_SDA2REL      = 108 # :nodoc:
        R_PPC_EMB_SDA21        = 109 # :nodoc:
        R_PPC_EMB_MRKREF       = 110 # :nodoc:
        R_PPC_EMB_RELSEC16     = 111 # :nodoc:
        R_PPC_EMB_RELST_LO     = 112 # :nodoc:
        R_PPC_EMB_RELST_HI     = 113 # :nodoc:
        R_PPC_EMB_RELST_HA     = 114 # :nodoc:
        R_PPC_EMB_BIT_FLD      = 115 # :nodoc:
        R_PPC_EMB_RELSDA       = 116 # :nodoc:
        R_PPC_PLTSEQ           = 119 # :nodoc:
        R_PPC_PLTCALL          = 120 # :nodoc:
        R_PPC_VLE_REL8         = 216 # :nodoc:
        R_PPC_VLE_REL15        = 217 # :nodoc:
        R_PPC_VLE_REL24        = 218 # :nodoc:
        R_PPC_VLE_LO16A        = 219 # :nodoc:
        R_PPC_VLE_LO16D        = 220 # :nodoc:
        R_PPC_VLE_HI16A        = 221 # :nodoc:
        R_PPC_VLE_HI16D        = 222 # :nodoc:
        R_PPC_VLE_HA16A        = 223 # :nodoc:
        R_PPC_VLE_HA16D        = 224 # :nodoc:
        R_PPC_VLE_SDA21        = 225 # :nodoc:
        R_PPC_VLE_SDA21_LO     = 226 # :nodoc:
        R_PPC_VLE_SDAREL_LO16A = 227 # :nodoc:
        R_PPC_VLE_SDAREL_LO16D = 228 # :nodoc:
        R_PPC_VLE_SDAREL_HI16A = 229 # :nodoc:
        R_PPC_VLE_SDAREL_HI16D = 230 # :nodoc:
        R_PPC_VLE_SDAREL_HA16A = 231 # :nodoc:
        R_PPC_VLE_SDAREL_HA16D = 232 # :nodoc:
        R_PPC_VLE_ADDR20       = 233 # :nodoc:
        R_PPC_REL16DX_HA       = 246 # :nodoc:
        R_PPC_IRELATIVE        = 248 # :nodoc:
        R_PPC_REL16            = 249 # :nodoc:
        R_PPC_REL16_LO         = 250 # :nodoc:
        R_PPC_REL16_HI         = 251 # :nodoc:
        R_PPC_REL16_HA         = 252 # :nodoc:
        R_PPC_GNU_VTINHERIT    = 253 # :nodoc:
        R_PPC_GNU_VTENTRY      = 254 # :nodoc:
        R_PPC_TOC16            = 255 # :nodoc:
      end
    end
  end
end
