# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of PRU.
      module PRU
        R_PRU_NONE            = 0 # :nodoc:
        R_PRU_16_PMEM         = 5 # :nodoc:
        R_PRU_U16_PMEMIMM     = 6 # :nodoc:
        R_PRU_BFD_RELOC_16    = 8 # :nodoc:
        R_PRU_U16             = 9 # :nodoc:
        R_PRU_32_PMEM         = 10 # :nodoc:
        R_PRU_BFD_RELOC_32    = 11 # :nodoc:
        R_PRU_S10_PCREL       = 14 # :nodoc:
        R_PRU_U8_PCREL        = 15 # :nodoc:
        R_PRU_LDI32           = 18 # :nodoc:
        R_PRU_GNU_BFD_RELOC_8 = 64 # :nodoc:
        R_PRU_GNU_DIFF8       = 65 # :nodoc:
        R_PRU_GNU_DIFF16      = 66 # :nodoc:
        R_PRU_GNU_DIFF32      = 67 # :nodoc:
        R_PRU_GNU_DIFF16_PMEM = 68 # :nodoc:
        R_PRU_GNU_DIFF32_PMEM = 69 # :nodoc:
        R_PRU_ILLEGAL         = 70 # :nodoc:
      end
    end
  end
end
