# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of RISCV.
      module RISCV
        R_RISCV_NONE              = 0 # :nodoc:
        R_RISCV_32                = 1 # :nodoc:
        R_RISCV_64                = 2 # :nodoc:
        R_RISCV_RELATIVE          = 3 # :nodoc:
        R_RISCV_COPY              = 4 # :nodoc:
        R_RISCV_JUMP_SLOT         = 5 # :nodoc:
        R_RISCV_TLS_DTPMOD32      = 6 # :nodoc:
        R_RISCV_TLS_DTPMOD64      = 7 # :nodoc:
        R_RISCV_TLS_DTPREL32      = 8 # :nodoc:
        R_RISCV_TLS_DTPREL64      = 9 # :nodoc:
        R_RISCV_TLS_TPREL32       = 10 # :nodoc:
        R_RISCV_TLS_TPREL64       = 11 # :nodoc:
        R_RISCV_TLSDESC           = 12 # :nodoc:
        R_RISCV_BRANCH            = 16 # :nodoc:
        R_RISCV_JAL               = 17 # :nodoc:
        R_RISCV_CALL              = 18 # :nodoc:
        R_RISCV_CALL_PLT          = 19 # :nodoc:
        R_RISCV_GOT_HI20          = 20 # :nodoc:
        R_RISCV_TLS_GOT_HI20      = 21 # :nodoc:
        R_RISCV_TLS_GD_HI20       = 22 # :nodoc:
        R_RISCV_PCREL_HI20        = 23 # :nodoc:
        R_RISCV_PCREL_LO12_I      = 24 # :nodoc:
        R_RISCV_PCREL_LO12_S      = 25 # :nodoc:
        R_RISCV_HI20              = 26 # :nodoc:
        R_RISCV_LO12_I            = 27 # :nodoc:
        R_RISCV_LO12_S            = 28 # :nodoc:
        R_RISCV_TPREL_HI20        = 29 # :nodoc:
        R_RISCV_TPREL_LO12_I      = 30 # :nodoc:
        R_RISCV_TPREL_LO12_S      = 31 # :nodoc:
        R_RISCV_TPREL_ADD         = 32 # :nodoc:
        R_RISCV_ADD8              = 33 # :nodoc:
        R_RISCV_ADD16             = 34 # :nodoc:
        R_RISCV_ADD32             = 35 # :nodoc:
        R_RISCV_ADD64             = 36 # :nodoc:
        R_RISCV_SUB8              = 37 # :nodoc:
        R_RISCV_SUB16             = 38 # :nodoc:
        R_RISCV_SUB32             = 39 # :nodoc:
        R_RISCV_SUB64             = 40 # :nodoc:
        R_RISCV_ALIGN             = 43 # :nodoc:
        R_RISCV_RVC_BRANCH        = 44 # :nodoc:
        R_RISCV_RVC_JUMP          = 45 # :nodoc:
        R_RISCV_RVC_LUI           = 46 # :nodoc:
        R_RISCV_GPREL_I           = 47 # :nodoc:
        R_RISCV_GPREL_S           = 48 # :nodoc:
        R_RISCV_TPREL_I           = 49 # :nodoc:
        R_RISCV_TPREL_S           = 50 # :nodoc:
        R_RISCV_RELAX             = 51 # :nodoc:
        R_RISCV_SUB6              = 52 # :nodoc:
        R_RISCV_SET6              = 53 # :nodoc:
        R_RISCV_SET8              = 54 # :nodoc:
        R_RISCV_SET16             = 55 # :nodoc:
        R_RISCV_SET32             = 56 # :nodoc:
        R_RISCV_32_PCREL          = 57 # :nodoc:
        R_RISCV_IRELATIVE         = 58 # :nodoc:
        R_RISCV_SET_ULEB128       = 60 # :nodoc:
        R_RISCV_SUB_ULEB128       = 61 # :nodoc:
        R_RISCV_TLSDESC_HI20      = 62 # :nodoc:
        R_RISCV_TLSDESC_LOAD_LO12 = 63 # :nodoc:
        R_RISCV_TLSDESC_ADD_LO12  = 64 # :nodoc:
        R_RISCV_TLSDESC_CALL      = 65 # :nodoc:
      end
    end
  end
end
