# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of RL78.
      module RL78
        R_RL78_NONE         = 0 # :nodoc:
        R_RL78_DIR32        = 1 # Was: R_RL78_32
        R_RL78_DIR24S       = 2 # Was: R_RL78_24
        R_RL78_DIR16        = 3 # :nodoc:
        R_RL78_DIR16U       = 4 # Was: R_RL78_16_UNS
        R_RL78_DIR16S       = 5 # Was: R_RL78_16
        R_RL78_DIR8         = 6 # :nodoc:
        R_RL78_DIR8U        = 7 # Was: R_RL78_8_UNS
        R_RL78_DIR8S        = 8 # Was: R_RL78_8
        R_RL78_DIR24S_PCREL = 9 # Was: R_RL78_24_PCREL
        R_RL78_DIR16S_PCREL = 10 # Was: R_RL78_16_PCREL
        R_RL78_DIR8S_PCREL  = 11 # Was: R_RL78_8_PCREL
        R_RL78_DIR16UL      = 12 # :nodoc:
        R_RL78_DIR16UW      = 13 # :nodoc:
        R_RL78_DIR8UL       = 14 # :nodoc:
        R_RL78_DIR8UW       = 15 # :nodoc:
        R_RL78_DIR32_REV    = 16 # :nodoc:
        R_RL78_DIR16_REV    = 17 # :nodoc:
        R_RL78_DIR3U_PCREL  = 18 # :nodoc:
        R_RL78_RH_RELAX     = 45 # Marks opcodes suitable for linker relaxation
        R_RL78_RH_SFR       = 46 # SFR addresses - internal use only
        R_RL78_RH_SADDR     = 47 # SADDR addresses - internal use only.
        R_RL78_ABS32        = 65 # :nodoc:
        R_RL78_ABS24S       = 66 # :nodoc:
        R_RL78_ABS16        = 67 # :nodoc:
        R_RL78_ABS16U       = 68 # :nodoc:
        R_RL78_ABS16S       = 69 # :nodoc:
        R_RL78_ABS8         = 70 # :nodoc:
        R_RL78_ABS8U        = 71 # :nodoc:
        R_RL78_ABS8S        = 72 # :nodoc:
        R_RL78_ABS24S_PCREL = 73 # :nodoc:
        R_RL78_ABS16S_PCREL = 74 # :nodoc:
        R_RL78_ABS8S_PCREL  = 75 # :nodoc:
        R_RL78_ABS16UL      = 76 # :nodoc:
        R_RL78_ABS16UW      = 77 # :nodoc:
        R_RL78_ABS8UL       = 78 # :nodoc:
        R_RL78_ABS8UW       = 79 # :nodoc:
        R_RL78_ABS32_REV    = 80 # :nodoc:
        R_RL78_ABS16_REV    = 81 # :nodoc:
        R_RL78_SYM          = 128 # :nodoc:
        R_RL78_OPneg        = 129 # :nodoc:
        R_RL78_OPadd        = 130 # :nodoc:
        R_RL78_OPsub        = 131 # :nodoc:
        R_RL78_OPmul        = 132 # :nodoc:
        R_RL78_OPdiv        = 133 # :nodoc:
        R_RL78_OPshla       = 134 # :nodoc:
        R_RL78_OPshra       = 135 # :nodoc:
        R_RL78_OPsctsize    = 136 # :nodoc:
        R_RL78_OPscttop     = 141 # :nodoc:
        R_RL78_OPand        = 144 # :nodoc:
        R_RL78_OPor         = 145 # :nodoc:
        R_RL78_OPxor        = 146 # :nodoc:
        R_RL78_OPnot        = 147 # :nodoc:
        R_RL78_OPmod        = 148 # :nodoc:
        R_RL78_OPromtop     = 149 # :nodoc:
        R_RL78_OPramtop     = 150 # :nodoc:
      end
    end
  end
end
