# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of RX.
      module RX
        R_RX_NONE         = 0 # :nodoc:
        R_RX_DIR32        = 1 # Was: R_RX_32
        R_RX_DIR24S       = 2 # Was: R_RX_24
        R_RX_DIR16        = 3 # :nodoc:
        R_RX_DIR16U       = 4 # Was: R_RX_16_UNS
        R_RX_DIR16S       = 5 # Was: R_RX_16
        R_RX_DIR8         = 6 # :nodoc:
        R_RX_DIR8U        = 7 # Was: R_RX_8_UNS
        R_RX_DIR8S        = 8 # Was: R_RX_8
        R_RX_DIR24S_PCREL = 9 # Was: R_RX_24_PCREL
        R_RX_DIR16S_PCREL = 10 # Was: R_RX_16_PCREL
        R_RX_DIR8S_PCREL  = 11 # Was: R_RX_8_PCREL
        R_RX_DIR16UL      = 12 # :nodoc:
        R_RX_DIR16UW      = 13 # :nodoc:
        R_RX_DIR8UL       = 14 # :nodoc:
        R_RX_DIR8UW       = 15 # :nodoc:
        R_RX_DIR32_REV    = 16 # :nodoc:
        R_RX_DIR16_REV    = 17 # :nodoc:
        R_RX_DIR3U_PCREL  = 18 # :nodoc:
        R_RX_RH_3_PCREL   = 32 # Like R_RX_DIR8S_PCREL but only 3-bits
        R_RX_RH_16_OP     = 33 # Like R_RX_DIR16 but for opcodes - always big endian
        R_RX_RH_24_OP     = 34 # Like R_RX_DIR24S but for opcodes - always big endian
        R_RX_RH_32_OP     = 35 # Like R_RX_DIR32 but for opcodes - always big endian
        R_RX_RH_24_UNS    = 36 # Like R_RX_DIR24S but for unsigned values
        R_RX_RH_8_NEG     = 37 # Like R_RX_DIR8 but -x is stored
        R_RX_RH_16_NEG    = 38 # Like R_RX_DIR16 but -x is stored
        R_RX_RH_24_NEG    = 39 # Like R_RX_DIR24S but -x is stored
        R_RX_RH_32_NEG    = 40 # Like R_RX_DIR32 but -x is stored
        R_RX_RH_DIFF      = 41 # Subtract from a previous relocation
        R_RX_RH_GPRELB    = 42 # Byte value, relative to __gp
        R_RX_RH_GPRELW    = 43 # Word value, relative to __gp
        R_RX_RH_GPRELL    = 44 # Long value, relative to __gp
        R_RX_RH_RELAX     = 45 # Marks opcodes suitable for linker relaxation
        R_RX_ABS32        = 65 # :nodoc:
        R_RX_ABS24S       = 66 # :nodoc:
        R_RX_ABS16        = 67 # :nodoc:
        R_RX_ABS16U       = 68 # :nodoc:
        R_RX_ABS16S       = 69 # :nodoc:
        R_RX_ABS8         = 70 # :nodoc:
        R_RX_ABS8U        = 71 # :nodoc:
        R_RX_ABS8S        = 72 # :nodoc:
        R_RX_ABS24S_PCREL = 73 # :nodoc:
        R_RX_ABS16S_PCREL = 74 # :nodoc:
        R_RX_ABS8S_PCREL  = 75 # :nodoc:
        R_RX_ABS16UL      = 76 # :nodoc:
        R_RX_ABS16UW      = 77 # :nodoc:
        R_RX_ABS8UL       = 78 # :nodoc:
        R_RX_ABS8UW       = 79 # :nodoc:
        R_RX_ABS32_REV    = 80 # :nodoc:
        R_RX_ABS16_REV    = 81 # :nodoc:
        R_RX_SYM          = 128 # :nodoc:
        R_RX_OPneg        = 129 # :nodoc:
        R_RX_OPadd        = 130 # :nodoc:
        R_RX_OPsub        = 131 # :nodoc:
        R_RX_OPmul        = 132 # :nodoc:
        R_RX_OPdiv        = 133 # :nodoc:
        R_RX_OPshla       = 134 # :nodoc:
        R_RX_OPshra       = 135 # :nodoc:
        R_RX_OPsctsize    = 136 # :nodoc:
        R_RX_OPscttop     = 141 # :nodoc:
        R_RX_OPand        = 144 # :nodoc:
        R_RX_OPor         = 145 # :nodoc:
        R_RX_OPxor        = 146 # :nodoc:
        R_RX_OPnot        = 147 # :nodoc:
        R_RX_OPmod        = 148 # :nodoc:
        R_RX_OPromtop     = 149 # :nodoc:
        R_RX_OPramtop     = 150 # :nodoc:
      end
    end
  end
end
