# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of S12Z.
      module S12Z
        R_S12Z_NONE       = 0 # :nodoc:
        R_S12Z_OPR        = 1 # :nodoc:
        R_S12Z_UKNWN_2    = 2 # :nodoc:
        R_S12Z_PCREL_7_15 = 3 # :nodoc:
        R_S12Z_EXT24      = 4 # :nodoc:
        R_S12Z_EXT18      = 5 # :nodoc:
        R_S12Z_CW32       = 6 # :nodoc:
        R_S12Z_EXT32      = 7 # :nodoc:
      end
    end
  end
end
