# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of S390.
      module S390
        R_390_NONE          = 0 # No reloc
        R_390_8             = 1 # Direct 8 bit
        R_390_12            = 2 # Direct 12 bit
        R_390_16            = 3 # Direct 16 bit
        R_390_32            = 4 # Direct 32 bit
        R_390_PC32          = 5 # PC relative 32 bit
        R_390_GOT12         = 6 # 12 bit GOT offset
        R_390_GOT32         = 7 # 32 bit GOT offset
        R_390_PLT32         = 8 # 32 bit PC relative PLT address
        R_390_COPY          = 9 # Copy symbol at runtime
        R_390_GLOB_DAT      = 10 # Create GOT entry
        R_390_JMP_SLOT      = 11 # Create PLT entry
        R_390_RELATIVE      = 12 # Adjust by program base
        R_390_GOTOFF32      = 13 # 32 bit offset to GOT
        R_390_GOTPC         = 14 # 32 bit PC relative offset to GOT
        R_390_GOT16         = 15 # 16 bit GOT offset
        R_390_PC16          = 16 # PC relative 16 bit
        R_390_PC16DBL       = 17 # PC relative 16 bit shifted by 1
        R_390_PLT16DBL      = 18 # 16 bit PC rel. PLT shifted by 1
        R_390_PC32DBL       = 19 # PC relative 32 bit shifted by 1
        R_390_PLT32DBL      = 20 # 32 bit PC rel. PLT shifted by 1
        R_390_GOTPCDBL      = 21 # 32 bit PC rel. GOT shifted by 1
        R_390_64            = 22 # Direct 64 bit
        R_390_PC64          = 23 # PC relative 64 bit
        R_390_GOT64         = 24 # 64 bit GOT offset
        R_390_PLT64         = 25 # 64 bit PC relative PLT address
        R_390_GOTENT        = 26 # 32 bit PC rel. to GOT entry >> 1
        R_390_GOTOFF16      = 27 # 16 bit offset to GOT
        R_390_GOTOFF64      = 28 # 64 bit offset to GOT
        R_390_GOTPLT12      = 29 # 12 bit offset to jump slot
        R_390_GOTPLT16      = 30 # 16 bit offset to jump slot
        R_390_GOTPLT32      = 31 # 32 bit offset to jump slot
        R_390_GOTPLT64      = 32 # 64 bit offset to jump slot
        R_390_GOTPLTENT     = 33 # 32 bit rel. offset to jump slot
        R_390_PLTOFF16      = 34 # 16 bit offset from GOT to PLT
        R_390_PLTOFF32      = 35 # 32 bit offset from GOT to PLT
        R_390_PLTOFF64      = 36 # 16 bit offset from GOT to PLT
        R_390_TLS_LOAD      = 37 # Tag for load insn in TLS code
        R_390_TLS_GDCALL    = 38 # :nodoc:
        R_390_TLS_LDCALL    = 39 # :nodoc:
        R_390_TLS_GD32      = 40 # :nodoc:
        R_390_TLS_GD64      = 41 # :nodoc:
        R_390_TLS_GOTIE12   = 42 # :nodoc:
        R_390_TLS_GOTIE32   = 43 # :nodoc:
        R_390_TLS_GOTIE64   = 44 # :nodoc:
        R_390_TLS_LDM32     = 45 # :nodoc:
        R_390_TLS_LDM64     = 46 # :nodoc:
        R_390_TLS_IE32      = 47 # :nodoc:
        R_390_TLS_IE64      = 48 # :nodoc:
        R_390_TLS_IEENT     = 49 # :nodoc:
        R_390_TLS_LE32      = 50 # :nodoc:
        R_390_TLS_LE64      = 51 # :nodoc:
        R_390_TLS_LDO32     = 52 # :nodoc:
        R_390_TLS_LDO64     = 53 # :nodoc:
        R_390_TLS_DTPMOD    = 54 # ID of module containing symbol
        R_390_TLS_DTPOFF    = 55 # Offset in TLS block
        R_390_TLS_TPOFF     = 56 # :nodoc:
        R_390_20            = 57 # Direct 20 bit
        R_390_GOT20         = 58 # 20 bit GOT offset
        R_390_GOTPLT20      = 59 # 20 bit offset to jump slot
        R_390_TLS_GOTIE20   = 60 # :nodoc:
        R_390_IRELATIVE     = 61 # IFUNC relocation
        R_390_PC12DBL       = 62 # PC relative 12 bit shifted by 1
        R_390_PLT12DBL      = 63 # 12 bit PC rel. PLT shifted by 1
        R_390_PC24DBL       = 64 # PC relative 24 bit shifted by 1
        R_390_PLT24DBL      = 65 # 24 bit PC rel. PLT shifted by 1
        R_390_GNU_VTINHERIT = 250 # :nodoc:
        R_390_GNU_VTENTRY   = 251 # :nodoc:
      end
    end
  end
end
