# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of SCORE.
      module SCORE
        R_SCORE_NONE          = 0 # :nodoc:
        R_SCORE_HI16          = 1 # :nodoc:
        R_SCORE_LO16          = 2 # :nodoc:
        R_SCORE_BCMP          = 3 # :nodoc:
        R_SCORE_24            = 4 # :nodoc:
        R_SCORE_PC19          = 5 # :nodoc:
        R_SCORE16_11          = 6 # :nodoc:
        R_SCORE16_PC8         = 7 # :nodoc:
        R_SCORE_ABS32         = 8 # :nodoc:
        R_SCORE_ABS16         = 9 # :nodoc:
        R_SCORE_DUMMY2        = 10 # :nodoc:
        R_SCORE_GP15          = 11 # :nodoc:
        R_SCORE_GNU_VTINHERIT = 12 # :nodoc:
        R_SCORE_GNU_VTENTRY   = 13 # :nodoc:
        R_SCORE_GOT15         = 14 # :nodoc:
        R_SCORE_GOT_LO16      = 15 # :nodoc:
        R_SCORE_CALL15        = 16 # :nodoc:
        R_SCORE_GPREL32       = 17 # :nodoc:
        R_SCORE_REL32         = 18 # :nodoc:
        R_SCORE_DUMMY_HI16    = 19 # :nodoc:
        R_SCORE_IMM30         = 20 # :nodoc:
        R_SCORE_IMM32         = 21 # :nodoc:
      end
    end
  end
end
