# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of SPARC.
      module SPARC
        R_SPARC_NONE             = 0 # :nodoc:
        R_SPARC_8                = 1 # :nodoc:
        R_SPARC_16               = 2 # :nodoc:
        R_SPARC_32               = 3 # :nodoc:
        R_SPARC_DISP8            = 4 # :nodoc:
        R_SPARC_DISP16           = 5 # :nodoc:
        R_SPARC_DISP32           = 6 # :nodoc:
        R_SPARC_WDISP30          = 7 # :nodoc:
        R_SPARC_WDISP22          = 8 # :nodoc:
        R_SPARC_HI22             = 9 # :nodoc:
        R_SPARC_22               = 10 # :nodoc:
        R_SPARC_13               = 11 # :nodoc:
        R_SPARC_LO10             = 12 # :nodoc:
        R_SPARC_GOT10            = 13 # :nodoc:
        R_SPARC_GOT13            = 14 # :nodoc:
        R_SPARC_GOT22            = 15 # :nodoc:
        R_SPARC_PC10             = 16 # :nodoc:
        R_SPARC_PC22             = 17 # :nodoc:
        R_SPARC_WPLT30           = 18 # :nodoc:
        R_SPARC_COPY             = 19 # :nodoc:
        R_SPARC_GLOB_DAT         = 20 # :nodoc:
        R_SPARC_JMP_SLOT         = 21 # :nodoc:
        R_SPARC_RELATIVE         = 22 # :nodoc:
        R_SPARC_UA32             = 23 # :nodoc:
        R_SPARC_PLT32            = 24 # :nodoc:
        R_SPARC_HIPLT22          = 25 # :nodoc:
        R_SPARC_LOPLT10          = 26 # :nodoc:
        R_SPARC_PCPLT32          = 27 # :nodoc:
        R_SPARC_PCPLT22          = 28 # :nodoc:
        R_SPARC_PCPLT10          = 29 # :nodoc:
        R_SPARC_10               = 30 # :nodoc:
        R_SPARC_11               = 31 # :nodoc:
        R_SPARC_64               = 32 # :nodoc:
        R_SPARC_OLO10            = 33 # :nodoc:
        R_SPARC_HH22             = 34 # :nodoc:
        R_SPARC_HM10             = 35 # :nodoc:
        R_SPARC_LM22             = 36 # :nodoc:
        R_SPARC_PC_HH22          = 37 # :nodoc:
        R_SPARC_PC_HM10          = 38 # :nodoc:
        R_SPARC_PC_LM22          = 39 # :nodoc:
        R_SPARC_WDISP16          = 40 # :nodoc:
        R_SPARC_WDISP19          = 41 # :nodoc:
        R_SPARC_UNUSED_42        = 42 # :nodoc:
        R_SPARC_7                = 43 # :nodoc:
        R_SPARC_5                = 44 # :nodoc:
        R_SPARC_6                = 45 # :nodoc:
        R_SPARC_DISP64           = 46 # :nodoc:
        R_SPARC_PLT64            = 47 # :nodoc:
        R_SPARC_HIX22            = 48 # :nodoc:
        R_SPARC_LOX10            = 49 # :nodoc:
        R_SPARC_H44              = 50 # :nodoc:
        R_SPARC_M44              = 51 # :nodoc:
        R_SPARC_L44              = 52 # :nodoc:
        R_SPARC_REGISTER         = 53 # :nodoc:
        R_SPARC_UA64             = 54 # :nodoc:
        R_SPARC_UA16             = 55 # :nodoc:
        R_SPARC_TLS_GD_HI22      = 56 # :nodoc:
        R_SPARC_TLS_GD_LO10      = 57 # :nodoc:
        R_SPARC_TLS_GD_ADD       = 58 # :nodoc:
        R_SPARC_TLS_GD_CALL      = 59 # :nodoc:
        R_SPARC_TLS_LDM_HI22     = 60 # :nodoc:
        R_SPARC_TLS_LDM_LO10     = 61 # :nodoc:
        R_SPARC_TLS_LDM_ADD      = 62 # :nodoc:
        R_SPARC_TLS_LDM_CALL     = 63 # :nodoc:
        R_SPARC_TLS_LDO_HIX22    = 64 # :nodoc:
        R_SPARC_TLS_LDO_LOX10    = 65 # :nodoc:
        R_SPARC_TLS_LDO_ADD      = 66 # :nodoc:
        R_SPARC_TLS_IE_HI22      = 67 # :nodoc:
        R_SPARC_TLS_IE_LO10      = 68 # :nodoc:
        R_SPARC_TLS_IE_LD        = 69 # :nodoc:
        R_SPARC_TLS_IE_LDX       = 70 # :nodoc:
        R_SPARC_TLS_IE_ADD       = 71 # :nodoc:
        R_SPARC_TLS_LE_HIX22     = 72 # :nodoc:
        R_SPARC_TLS_LE_LOX10     = 73 # :nodoc:
        R_SPARC_TLS_DTPMOD32     = 74 # :nodoc:
        R_SPARC_TLS_DTPMOD64     = 75 # :nodoc:
        R_SPARC_TLS_DTPOFF32     = 76 # :nodoc:
        R_SPARC_TLS_DTPOFF64     = 77 # :nodoc:
        R_SPARC_TLS_TPOFF32      = 78 # :nodoc:
        R_SPARC_TLS_TPOFF64      = 79 # :nodoc:
        R_SPARC_GOTDATA_HIX22    = 80 # :nodoc:
        R_SPARC_GOTDATA_LOX10    = 81 # :nodoc:
        R_SPARC_GOTDATA_OP_HIX22 = 82 # :nodoc:
        R_SPARC_GOTDATA_OP_LOX10 = 83 # :nodoc:
        R_SPARC_GOTDATA_OP       = 84 # :nodoc:
        R_SPARC_H34              = 85 # :nodoc:
        R_SPARC_SIZE32           = 86 # :nodoc:
        R_SPARC_SIZE64           = 87 # :nodoc:
        R_SPARC_WDISP10          = 88 # :nodoc:
        R_SPARC_JMP_IREL         = 248 # :nodoc:
        R_SPARC_IRELATIVE        = 249 # :nodoc:
        R_SPARC_GNU_VTINHERIT    = 250 # :nodoc:
        R_SPARC_GNU_VTENTRY      = 251 # :nodoc:
        R_SPARC_REV32            = 252 # :nodoc:
      end
    end
  end
end
