# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of SPU.
      module SPU
        R_SPU_NONE      = 0 # :nodoc:
        R_SPU_ADDR10    = 1 # :nodoc:
        R_SPU_ADDR16    = 2 # :nodoc:
        R_SPU_ADDR16_HI = 3 # :nodoc:
        R_SPU_ADDR16_LO = 4 # :nodoc:
        R_SPU_ADDR18    = 5 # :nodoc:
        R_SPU_ADDR32    = 6 # :nodoc:
        R_SPU_REL16     = 7 # :nodoc:
        R_SPU_ADDR7     = 8 # :nodoc:
        R_SPU_REL9      = 9 # :nodoc:
        R_SPU_REL9I     = 10 # :nodoc:
        R_SPU_ADDR10I   = 11 # :nodoc:
        R_SPU_ADDR16I   = 12 # :nodoc:
        R_SPU_REL32     = 13 # :nodoc:
        R_SPU_ADDR16X   = 14 # :nodoc:
        R_SPU_PPU32     = 15 # :nodoc:
        R_SPU_PPU64     = 16 # :nodoc:
        R_SPU_ADD_PIC   = 17 # :nodoc:
      end
    end
  end
end
