# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of TIC6X.
      module TIC6X
        R_C6000_NONE          = 0 # :nodoc:
        R_C6000_ABS32         = 1 # :nodoc:
        R_C6000_ABS16         = 2 # :nodoc:
        R_C6000_ABS8          = 3 # :nodoc:
        R_C6000_PCR_S21       = 4 # :nodoc:
        R_C6000_PCR_S12       = 5 # :nodoc:
        R_C6000_PCR_S10       = 6 # :nodoc:
        R_C6000_PCR_S7        = 7 # :nodoc:
        R_C6000_ABS_S16       = 8 # :nodoc:
        R_C6000_ABS_L16       = 9 # :nodoc:
        R_C6000_ABS_H16       = 10 # :nodoc:
        R_C6000_SBR_U15_B     = 11 # :nodoc:
        R_C6000_SBR_U15_H     = 12 # :nodoc:
        R_C6000_SBR_U15_W     = 13 # :nodoc:
        R_C6000_SBR_S16       = 14 # :nodoc:
        R_C6000_SBR_L16_B     = 15 # :nodoc:
        R_C6000_SBR_L16_H     = 16 # :nodoc:
        R_C6000_SBR_L16_W     = 17 # :nodoc:
        R_C6000_SBR_H16_B     = 18 # :nodoc:
        R_C6000_SBR_H16_H     = 19 # :nodoc:
        R_C6000_SBR_H16_W     = 20 # :nodoc:
        R_C6000_SBR_GOT_U15_W = 21 # :nodoc:
        R_C6000_SBR_GOT_L16_W = 22 # :nodoc:
        R_C6000_SBR_GOT_H16_W = 23 # :nodoc:
        R_C6000_DSBT_INDEX    = 24 # :nodoc:
        R_C6000_PREL31        = 25 # :nodoc:
        R_C6000_COPY          = 26 # :nodoc:
        R_C6000_JUMP_SLOT     = 27 # :nodoc:
        R_C6000_EHTYPE        = 28 # :nodoc:
        R_C6000_PCR_H16       = 29 # :nodoc:
        R_C6000_PCR_L16       = 30 # :nodoc:
        R_C6000_ALIGN         = 253 # :nodoc:
        R_C6000_FPHEAD        = 254 # :nodoc:
        R_C6000_NOCMP         = 255 # :nodoc:
      end
    end
  end
end
