# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of TILEPRO.
      module TILEPRO
        R_TILEPRO_NONE               = 0 # :nodoc:
        R_TILEPRO_32                 = 1 # :nodoc:
        R_TILEPRO_16                 = 2 # :nodoc:
        R_TILEPRO_8                  = 3 # :nodoc:
        R_TILEPRO_32_PCREL           = 4 # :nodoc:
        R_TILEPRO_16_PCREL           = 5 # :nodoc:
        R_TILEPRO_8_PCREL            = 6 # :nodoc:
        R_TILEPRO_LO16               = 7 # :nodoc:
        R_TILEPRO_HI16               = 8 # :nodoc:
        R_TILEPRO_HA16               = 9 # :nodoc:
        R_TILEPRO_COPY               = 10 # :nodoc:
        R_TILEPRO_GLOB_DAT           = 11 # :nodoc:
        R_TILEPRO_JMP_SLOT           = 12 # :nodoc:
        R_TILEPRO_RELATIVE           = 13 # :nodoc:
        R_TILEPRO_BROFF_X1           = 14 # :nodoc:
        R_TILEPRO_JOFFLONG_X1        = 15 # :nodoc:
        R_TILEPRO_JOFFLONG_X1_PLT    = 16 # :nodoc:
        R_TILEPRO_IMM8_X0            = 17 # :nodoc:
        R_TILEPRO_IMM8_Y0            = 18 # :nodoc:
        R_TILEPRO_IMM8_X1            = 19 # :nodoc:
        R_TILEPRO_IMM8_Y1            = 20 # :nodoc:
        R_TILEPRO_MT_IMM15_X1        = 21 # :nodoc:
        R_TILEPRO_MF_IMM15_X1        = 22 # :nodoc:
        R_TILEPRO_IMM16_X0           = 23 # :nodoc:
        R_TILEPRO_IMM16_X1           = 24 # :nodoc:
        R_TILEPRO_IMM16_X0_LO        = 25 # :nodoc:
        R_TILEPRO_IMM16_X1_LO        = 26 # :nodoc:
        R_TILEPRO_IMM16_X0_HI        = 27 # :nodoc:
        R_TILEPRO_IMM16_X1_HI        = 28 # :nodoc:
        R_TILEPRO_IMM16_X0_HA        = 29 # :nodoc:
        R_TILEPRO_IMM16_X1_HA        = 30 # :nodoc:
        R_TILEPRO_IMM16_X0_PCREL     = 31 # :nodoc:
        R_TILEPRO_IMM16_X1_PCREL     = 32 # :nodoc:
        R_TILEPRO_IMM16_X0_LO_PCREL  = 33 # :nodoc:
        R_TILEPRO_IMM16_X1_LO_PCREL  = 34 # :nodoc:
        R_TILEPRO_IMM16_X0_HI_PCREL  = 35 # :nodoc:
        R_TILEPRO_IMM16_X1_HI_PCREL  = 36 # :nodoc:
        R_TILEPRO_IMM16_X0_HA_PCREL  = 37 # :nodoc:
        R_TILEPRO_IMM16_X1_HA_PCREL  = 38 # :nodoc:
        R_TILEPRO_IMM16_X0_GOT       = 39 # :nodoc:
        R_TILEPRO_IMM16_X1_GOT       = 40 # :nodoc:
        R_TILEPRO_IMM16_X0_GOT_LO    = 41 # :nodoc:
        R_TILEPRO_IMM16_X1_GOT_LO    = 42 # :nodoc:
        R_TILEPRO_IMM16_X0_GOT_HI    = 43 # :nodoc:
        R_TILEPRO_IMM16_X1_GOT_HI    = 44 # :nodoc:
        R_TILEPRO_IMM16_X0_GOT_HA    = 45 # :nodoc:
        R_TILEPRO_IMM16_X1_GOT_HA    = 46 # :nodoc:
        R_TILEPRO_MMSTART_X0         = 47 # :nodoc:
        R_TILEPRO_MMEND_X0           = 48 # :nodoc:
        R_TILEPRO_MMSTART_X1         = 49 # :nodoc:
        R_TILEPRO_MMEND_X1           = 50 # :nodoc:
        R_TILEPRO_SHAMT_X0           = 51 # :nodoc:
        R_TILEPRO_SHAMT_X1           = 52 # :nodoc:
        R_TILEPRO_SHAMT_Y0           = 53 # :nodoc:
        R_TILEPRO_SHAMT_Y1           = 54 # :nodoc:
        R_TILEPRO_DEST_IMM8_X1       = 55 # :nodoc:
        R_TILEPRO_TLS_GD_CALL        = 60 # :nodoc:
        R_TILEPRO_IMM8_X0_TLS_GD_ADD = 61 # :nodoc:
        R_TILEPRO_IMM8_X1_TLS_GD_ADD = 62 # :nodoc:
        R_TILEPRO_IMM8_Y0_TLS_GD_ADD = 63 # :nodoc:
        R_TILEPRO_IMM8_Y1_TLS_GD_ADD = 64 # :nodoc:
        R_TILEPRO_TLS_IE_LOAD        = 65 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_GD    = 66 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_GD    = 67 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_GD_LO = 68 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_GD_LO = 69 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_GD_HI = 70 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_GD_HI = 71 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_GD_HA = 72 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_GD_HA = 73 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_IE    = 74 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_IE    = 75 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_IE_LO = 76 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_IE_LO = 77 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_IE_HI = 78 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_IE_HI = 79 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_IE_HA = 80 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_IE_HA = 81 # :nodoc:
        R_TILEPRO_TLS_DTPMOD32       = 82 # :nodoc:
        R_TILEPRO_TLS_DTPOFF32       = 83 # :nodoc:
        R_TILEPRO_TLS_TPOFF32        = 84 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_LE    = 85 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_LE    = 86 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_LE_LO = 87 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_LE_LO = 88 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_LE_HI = 89 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_LE_HI = 90 # :nodoc:
        R_TILEPRO_IMM16_X0_TLS_LE_HA = 91 # :nodoc:
        R_TILEPRO_IMM16_X1_TLS_LE_HA = 92 # :nodoc:
        R_TILEPRO_GNU_VTINHERIT      = 128 # :nodoc:
        R_TILEPRO_GNU_VTENTRY        = 129 # :nodoc:
      end
    end
  end
end
