# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of TILEGX.
      module TILEGX
        R_TILEGX_NONE                        = 0 # :nodoc:
        R_TILEGX_64                          = 1 # :nodoc:
        R_TILEGX_32                          = 2 # :nodoc:
        R_TILEGX_16                          = 3 # :nodoc:
        R_TILEGX_8                           = 4 # :nodoc:
        R_TILEGX_64_PCREL                    = 5 # :nodoc:
        R_TILEGX_32_PCREL                    = 6 # :nodoc:
        R_TILEGX_16_PCREL                    = 7 # :nodoc:
        R_TILEGX_8_PCREL                     = 8 # :nodoc:
        R_TILEGX_HW0                         = 9 # :nodoc:
        R_TILEGX_HW1                         = 10 # :nodoc:
        R_TILEGX_HW2                         = 11 # :nodoc:
        R_TILEGX_HW3                         = 12 # :nodoc:
        R_TILEGX_HW0_LAST                    = 13 # :nodoc:
        R_TILEGX_HW1_LAST                    = 14 # :nodoc:
        R_TILEGX_HW2_LAST                    = 15 # :nodoc:
        R_TILEGX_COPY                        = 16 # :nodoc:
        R_TILEGX_GLOB_DAT                    = 17 # :nodoc:
        R_TILEGX_JMP_SLOT                    = 18 # :nodoc:
        R_TILEGX_RELATIVE                    = 19 # :nodoc:
        R_TILEGX_BROFF_X1                    = 20 # :nodoc:
        R_TILEGX_JUMPOFF_X1                  = 21 # :nodoc:
        R_TILEGX_JUMPOFF_X1_PLT              = 22 # :nodoc:
        R_TILEGX_IMM8_X0                     = 23 # :nodoc:
        R_TILEGX_IMM8_Y0                     = 24 # :nodoc:
        R_TILEGX_IMM8_X1                     = 25 # :nodoc:
        R_TILEGX_IMM8_Y1                     = 26 # :nodoc:
        R_TILEGX_DEST_IMM8_X1                = 27 # :nodoc:
        R_TILEGX_MT_IMM14_X1                 = 28 # :nodoc:
        R_TILEGX_MF_IMM14_X1                 = 29 # :nodoc:
        R_TILEGX_MMSTART_X0                  = 30 # :nodoc:
        R_TILEGX_MMEND_X0                    = 31 # :nodoc:
        R_TILEGX_SHAMT_X0                    = 32 # :nodoc:
        R_TILEGX_SHAMT_X1                    = 33 # :nodoc:
        R_TILEGX_SHAMT_Y0                    = 34 # :nodoc:
        R_TILEGX_SHAMT_Y1                    = 35 # :nodoc:
        R_TILEGX_IMM16_X0_HW0                = 36 # :nodoc:
        R_TILEGX_IMM16_X1_HW0                = 37 # :nodoc:
        R_TILEGX_IMM16_X0_HW1                = 38 # :nodoc:
        R_TILEGX_IMM16_X1_HW1                = 39 # :nodoc:
        R_TILEGX_IMM16_X0_HW2                = 40 # :nodoc:
        R_TILEGX_IMM16_X1_HW2                = 41 # :nodoc:
        R_TILEGX_IMM16_X0_HW3                = 42 # :nodoc:
        R_TILEGX_IMM16_X1_HW3                = 43 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_LAST           = 44 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_LAST           = 45 # :nodoc:
        R_TILEGX_IMM16_X0_HW1_LAST           = 46 # :nodoc:
        R_TILEGX_IMM16_X1_HW1_LAST           = 47 # :nodoc:
        R_TILEGX_IMM16_X0_HW2_LAST           = 48 # :nodoc:
        R_TILEGX_IMM16_X1_HW2_LAST           = 49 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_PCREL          = 50 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_PCREL          = 51 # :nodoc:
        R_TILEGX_IMM16_X0_HW1_PCREL          = 52 # :nodoc:
        R_TILEGX_IMM16_X1_HW1_PCREL          = 53 # :nodoc:
        R_TILEGX_IMM16_X0_HW2_PCREL          = 54 # :nodoc:
        R_TILEGX_IMM16_X1_HW2_PCREL          = 55 # :nodoc:
        R_TILEGX_IMM16_X0_HW3_PCREL          = 56 # :nodoc:
        R_TILEGX_IMM16_X1_HW3_PCREL          = 57 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_LAST_PCREL     = 58 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_LAST_PCREL     = 59 # :nodoc:
        R_TILEGX_IMM16_X0_HW1_LAST_PCREL     = 60 # :nodoc:
        R_TILEGX_IMM16_X1_HW1_LAST_PCREL     = 61 # :nodoc:
        R_TILEGX_IMM16_X0_HW2_LAST_PCREL     = 62 # :nodoc:
        R_TILEGX_IMM16_X1_HW2_LAST_PCREL     = 63 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_GOT            = 64 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_GOT            = 65 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_PLT_PCREL      = 66 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_PLT_PCREL      = 67 # :nodoc:
        R_TILEGX_IMM16_X0_HW1_PLT_PCREL      = 68 # :nodoc:
        R_TILEGX_IMM16_X1_HW1_PLT_PCREL      = 69 # :nodoc:
        R_TILEGX_IMM16_X0_HW2_PLT_PCREL      = 70 # :nodoc:
        R_TILEGX_IMM16_X1_HW2_PLT_PCREL      = 71 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_LAST_GOT       = 72 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_LAST_GOT       = 73 # :nodoc:
        R_TILEGX_IMM16_X0_HW1_LAST_GOT       = 74 # :nodoc:
        R_TILEGX_IMM16_X1_HW1_LAST_GOT       = 75 # :nodoc:
        R_TILEGX_IMM16_X0_HW3_PLT_PCREL      = 76 # :nodoc:
        R_TILEGX_IMM16_X1_HW3_PLT_PCREL      = 77 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_TLS_GD         = 78 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_TLS_GD         = 79 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_TLS_LE         = 80 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_TLS_LE         = 81 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_LAST_TLS_LE    = 82 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_LAST_TLS_LE    = 83 # :nodoc:
        R_TILEGX_IMM16_X0_HW1_LAST_TLS_LE    = 84 # :nodoc:
        R_TILEGX_IMM16_X1_HW1_LAST_TLS_LE    = 85 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_LAST_TLS_GD    = 86 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_LAST_TLS_GD    = 87 # :nodoc:
        R_TILEGX_IMM16_X0_HW1_LAST_TLS_GD    = 88 # :nodoc:
        R_TILEGX_IMM16_X1_HW1_LAST_TLS_GD    = 89 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_TLS_IE         = 92 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_TLS_IE         = 93 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_LAST_PLT_PCREL = 94 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_LAST_PLT_PCREL = 95 # :nodoc:
        R_TILEGX_IMM16_X0_HW1_LAST_PLT_PCREL = 96 # :nodoc:
        R_TILEGX_IMM16_X1_HW1_LAST_PLT_PCREL = 97 # :nodoc:
        R_TILEGX_IMM16_X0_HW2_LAST_PLT_PCREL = 98 # :nodoc:
        R_TILEGX_IMM16_X1_HW2_LAST_PLT_PCREL = 99 # :nodoc:
        R_TILEGX_IMM16_X0_HW0_LAST_TLS_IE    = 100 # :nodoc:
        R_TILEGX_IMM16_X1_HW0_LAST_TLS_IE    = 101 # :nodoc:
        R_TILEGX_IMM16_X0_HW1_LAST_TLS_IE    = 102 # :nodoc:
        R_TILEGX_IMM16_X1_HW1_LAST_TLS_IE    = 103 # :nodoc:
        R_TILEGX_TLS_DTPMOD64                = 106 # :nodoc:
        R_TILEGX_TLS_DTPOFF64                = 107 # :nodoc:
        R_TILEGX_TLS_TPOFF64                 = 108 # :nodoc:
        R_TILEGX_TLS_DTPMOD32                = 109 # :nodoc:
        R_TILEGX_TLS_DTPOFF32                = 110 # :nodoc:
        R_TILEGX_TLS_TPOFF32                 = 111 # :nodoc:
        R_TILEGX_TLS_GD_CALL                 = 112 # :nodoc:
        R_TILEGX_IMM8_X0_TLS_GD_ADD          = 113 # :nodoc:
        R_TILEGX_IMM8_X1_TLS_GD_ADD          = 114 # :nodoc:
        R_TILEGX_IMM8_Y0_TLS_GD_ADD          = 115 # :nodoc:
        R_TILEGX_IMM8_Y1_TLS_GD_ADD          = 116 # :nodoc:
        R_TILEGX_TLS_IE_LOAD                 = 117 # :nodoc:
        R_TILEGX_IMM8_X0_TLS_ADD             = 118 # :nodoc:
        R_TILEGX_IMM8_X1_TLS_ADD             = 119 # :nodoc:
        R_TILEGX_IMM8_Y0_TLS_ADD             = 120 # :nodoc:
        R_TILEGX_IMM8_Y1_TLS_ADD             = 121 # :nodoc:
        R_TILEGX_GNU_VTINHERIT               = 128 # :nodoc:
        R_TILEGX_GNU_VTENTRY                 = 129 # :nodoc:
      end
    end
  end
end
