# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of V800.
      module V800
        R_V800_NONE      = 0 # :nodoc:
        R_V810_NONE      = 48 # :nodoc:
        R_V810_BYTE      = 49 # :nodoc:
        R_V810_HWORD     = 50 # :nodoc:
        R_V810_WORD      = 51 # :nodoc:
        R_V810_WLO       = 52 # :nodoc:
        R_V810_WHI       = 53 # :nodoc:
        R_V810_WHI1      = 54 # :nodoc:
        R_V810_GPBYTE    = 55 # :nodoc:
        R_V810_GPHWORD   = 56 # :nodoc:
        R_V810_GPWORD    = 57 # :nodoc:
        R_V810_GPWLO     = 58 # :nodoc:
        R_V810_GPWHI     = 59 # :nodoc:
        R_V810_GPWHI1    = 60 # :nodoc:
        R_V850_HWLO      = 61 # :nodoc:
        R_V850_EP7BIT    = 63 # :nodoc:
        R_V850_EPHBYTE   = 64 # :nodoc:
        R_V850_EPWBYTE   = 65 # :nodoc:
        R_V850_REGHWLO   = 66 # :nodoc:
        R_V850_GPHWLO    = 68 # :nodoc:
        R_V850_PCR22     = 70 # :nodoc:
        R_V850_BLO       = 71 # :nodoc:
        R_V850_EP4BIT    = 72 # :nodoc:
        R_V850_EP5BIT    = 73 # :nodoc:
        R_V850_REGBLO    = 74 # :nodoc:
        R_V850_GPBLO     = 75 # :nodoc:
        R_V810_WLO_1     = 76 # :nodoc:
        R_V810_GPWLO_1   = 77 # :nodoc:
        R_V850_BLO_1     = 78 # :nodoc:
        R_V850_HWLO_1    = 79 # :nodoc:
        R_V850_GPBLO_1   = 81 # :nodoc:
        R_V850_GPHWLO_1  = 82 # :nodoc:
        R_V850_EPBLO     = 84 # :nodoc:
        R_V850_EPHWLO    = 85 # :nodoc:
        R_V850_EPWLO_N   = 87 # :nodoc:
        R_V850_PC32      = 88 # :nodoc:
        R_V850_W23BIT    = 89 # :nodoc:
        R_V850_GPW23BIT  = 90 # :nodoc:
        R_V850_EPW23BIT  = 91 # :nodoc:
        R_V850_B23BIT    = 92 # :nodoc:
        R_V850_GPB23BIT  = 93 # :nodoc:
        R_V850_EPB23BIT  = 94 # :nodoc:
        R_V850_PC16U     = 95 # :nodoc:
        R_V850_PC17      = 96 # :nodoc:
        R_V850_DW8       = 97 # :nodoc:
        R_V850_GPDW8     = 98 # :nodoc:
        R_V850_EPDW8     = 99 # :nodoc:
        R_V850_PC9       = 100 # :nodoc:
        R_V810_REGBYTE   = 101 # :nodoc:
        R_V810_REGHWORD  = 102 # :nodoc:
        R_V810_REGWORD   = 103 # :nodoc:
        R_V810_REGWLO    = 104 # :nodoc:
        R_V810_REGWHI    = 105 # :nodoc:
        R_V810_REGWHI1   = 106 # :nodoc:
        R_V850_REGW23BIT = 107 # :nodoc:
        R_V850_REGB23BIT = 108 # :nodoc:
        R_V850_REGDW8    = 109 # :nodoc:
        R_V810_EPBYTE    = 110 # :nodoc:
        R_V810_EPHWORD   = 111 # :nodoc:
        R_V810_EPWORD    = 112 # :nodoc:
        R_V850_WLO23     = 113 # :nodoc:
        R_V850_WORD_E    = 114 # :nodoc:
        R_V850_REGWORD_E = 115 # :nodoc:
        R_V850_WORD      = 116 # :nodoc:
        R_V850_GPWORD    = 117 # :nodoc:
        R_V850_REGWORD   = 118 # :nodoc:
        R_V850_EPWORD    = 119 # :nodoc:
        R_V810_TPBYTE    = 120 # :nodoc:
        R_V810_TPHWORD   = 121 # :nodoc:
        R_V810_TPWORD    = 122 # :nodoc:
        R_V810_TPWLO     = 123 # :nodoc:
        R_V810_TPWHI     = 124 # :nodoc:
        R_V810_TPWHI1    = 125 # :nodoc:
        R_V850_TPHWLO    = 126 # :nodoc:
        R_V850_TPBLO     = 127 # :nodoc:
        R_V810_TPWLO_1   = 128 # :nodoc:
        R_V850_TPBLO_1   = 129 # :nodoc:
        R_V850_TPHWLO_1  = 130 # :nodoc:
        R_V850_TP23BIT   = 131 # :nodoc:
        R_V850_TPW23BIT  = 132 # :nodoc:
        R_V850_TPDW8     = 133 # :nodoc:
        R_V810_ABS32     = 160 # :nodoc:
        R_V850_SYM       = 224 # :nodoc:
        R_V850_OPadd     = 225 # :nodoc:
        R_V850_OPsub     = 226 # :nodoc:
        R_V850_OPsctsize = 227 # :nodoc:
        R_V850_OPscttop  = 228 # :nodoc:
      end
    end
  end
end
