# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of V850.
      module V850
        R_V850_NONE                   = 0 # :nodoc:
        R_V850_9_PCREL                = 1 # :nodoc:
        R_V850_22_PCREL               = 2 # :nodoc:
        R_V850_HI16_S                 = 3 # :nodoc:
        R_V850_HI16                   = 4 # :nodoc:
        R_V850_LO16                   = 5 # :nodoc:
        R_V850_ABS32                  = 6 # :nodoc:
        R_V850_16                     = 7 # :nodoc:
        R_V850_8                      = 8 # :nodoc:
        R_V850_SDA_16_16_OFFSET       = 9 # For ld.b, st.b, set1, clr1, not1, tst1, movea, movhi
        R_V850_SDA_15_16_OFFSET       = 10 # For ld.w, ld.h, ld.hu, st.w, st.h
        R_V850_ZDA_16_16_OFFSET       = 11 # For ld.b, st.b, set1, clr1, not1, tst1, movea, movhi
        R_V850_ZDA_15_16_OFFSET       = 12 # For ld.w, ld.h, ld.hu, st.w, st.h
        R_V850_TDA_6_8_OFFSET         = 13 # For sst.w, sld.w
        R_V850_TDA_7_8_OFFSET         = 14 # For sst.h, sld.h
        R_V850_TDA_7_7_OFFSET         = 15 # For sst.b, sld.b
        R_V850_TDA_16_16_OFFSET       = 16 # For set1, clr1, not1, tst1, movea, movhi
        R_V850_TDA_4_5_OFFSET         = 17 # For sld.hu
        R_V850_TDA_4_4_OFFSET         = 18 # For sld.bu
        R_V850_SDA_16_16_SPLIT_OFFSET = 19 # For ld.bu
        R_V850_ZDA_16_16_SPLIT_OFFSET = 20 # For ld.bu
        R_V850_CALLT_6_7_OFFSET       = 21 # For callt
        R_V850_CALLT_16_16_OFFSET     = 22 # For callt
        R_V850_GNU_VTINHERIT          = 23 # :nodoc:
        R_V850_GNU_VTENTRY            = 24 # :nodoc:
        R_V850_LONGCALL               = 25 # :nodoc:
        R_V850_LONGJUMP               = 26 # :nodoc:
        R_V850_ALIGN                  = 27 # :nodoc:
        R_V850_REL32                  = 28 # :nodoc:
        R_V850_LO16_SPLIT_OFFSET      = 29 # For ld.bu
        R_V850_16_PCREL               = 30 # For loop
        R_V850_17_PCREL               = 31 # For br
        R_V850_23                     = 32 # For 23bit ld.[w,h,hu,b,bu],st.[w,h,b]
        R_V850_32_PCREL               = 33 # For jr32, jarl32
        R_V850_32_ABS                 = 34 # For jmp32
        R_V850_16_SPLIT_OFFSET        = 35 # For ld.bu
        R_V850_16_S1                  = 36 # For ld.w, ld.h st.w st.h
        R_V850_LO16_S1                = 37 # For ld.w, ld.h st.w st.h
        R_V850_CALLT_15_16_OFFSET     = 38 # For ld.w, ld.h, ld.hu, st.w, st.h
        R_V850_32_GOTPCREL            = 39 # GLOBAL_OFFSET_TABLE from pc
        R_V850_16_GOT                 = 40 # GOT ENTRY from gp
        R_V850_32_GOT                 = 41 # :nodoc:
        R_V850_22_PLT                 = 42 # For jr
        R_V850_32_PLT                 = 43 # For jr32
        R_V850_COPY                   = 44 # :nodoc:
        R_V850_GLOB_DAT               = 45 # :nodoc:
        R_V850_JMP_SLOT               = 46 # :nodoc:
        R_V850_RELATIVE               = 47 # :nodoc:
        R_V850_16_GOTOFF              = 48 # From gp
        R_V850_32_GOTOFF              = 49 # :nodoc:
        R_V850_CODE                   = 50 # :nodoc:
        R_V850_DATA                   = 51 # For loop
      end
    end
  end
end
