# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of VAX.
      module VAX
        R_VAX_NONE          = 0 # No reloc
        R_VAX_32            = 1 # Direct 32 bit
        R_VAX_16            = 2 # Direct 16 bit
        R_VAX_8             = 3 # Direct 8 bit
        R_VAX_PC32          = 4 # PC relative 32 bit
        R_VAX_PC16          = 5 # PC relative 16 bit
        R_VAX_PC8           = 6 # PC relative 8 bit
        R_VAX_GOT32         = 7 # 32 bit PC relative GOT entry
        R_VAX_PLT32         = 13 # 32 bit PC relative PLT address
        R_VAX_COPY          = 19 # Copy symbol at runtime
        R_VAX_GLOB_DAT      = 20 # Create GOT entry
        R_VAX_JMP_SLOT      = 21 # Create PLT entry
        R_VAX_RELATIVE      = 22 # Adjust by program base
        R_VAX_GNU_VTINHERIT = 23 # :nodoc:
        R_VAX_GNU_VTENTRY   = 24 # :nodoc:
      end
    end
  end
end
