# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of VISIUM.
      module VISIUM
        R_VISIUM_NONE          = 0 # :nodoc:
        R_VISIUM_8             = 1 # :nodoc:
        R_VISIUM_16            = 2 # :nodoc:
        R_VISIUM_32            = 3 # :nodoc:
        R_VISIUM_8_PCREL       = 4 # :nodoc:
        R_VISIUM_16_PCREL      = 5 # :nodoc:
        R_VISIUM_32_PCREL      = 6 # :nodoc:
        R_VISIUM_PC16          = 7 # :nodoc:
        R_VISIUM_HI16          = 8 # :nodoc:
        R_VISIUM_LO16          = 9 # :nodoc:
        R_VISIUM_IM16          = 10 # :nodoc:
        R_VISIUM_HI16_PCREL    = 11 # :nodoc:
        R_VISIUM_LO16_PCREL    = 12 # :nodoc:
        R_VISIUM_IM16_PCREL    = 13 # :nodoc:
        R_VISIUM_GNU_VTINHERIT = 200 # :nodoc:
        R_VISIUM_GNU_VTENTRY   = 201 # :nodoc:
      end
    end
  end
end
