# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of WASM32.
      module WASM32
        R_WASM32_NONE = 0 # :nodoc:
        R_WASM32_32   = 1 # :nodoc:
      end
    end
  end
end
