# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of X86_64.
      module X86_64
        R_X86_64_NONE                   = 0 # No reloc
        R_X86_64_64                     = 1 # Direct 64 bit
        R_X86_64_PC32                   = 2 # PC relative 32 bit signed
        R_X86_64_GOT32                  = 3 # 32 bit GOT entry
        R_X86_64_PLT32                  = 4 # 32 bit PLT address
        R_X86_64_COPY                   = 5 # Copy symbol at runtime
        R_X86_64_GLOB_DAT               = 6 # Create GOT entry
        R_X86_64_JUMP_SLOT              = 7 # Create PLT entry
        R_X86_64_RELATIVE               = 8 # Adjust by program base
        R_X86_64_GOTPCREL               = 9 # :nodoc:
        R_X86_64_32                     = 10 # Direct 32 bit zero extended
        R_X86_64_32S                    = 11 # Direct 32 bit sign extended
        R_X86_64_16                     = 12 # Direct 16 bit zero extended
        R_X86_64_PC16                   = 13 # 16 bit sign extended pc relative
        R_X86_64_8                      = 14 # Direct 8 bit sign extended
        R_X86_64_PC8                    = 15 # 8 bit sign extended pc relative
        R_X86_64_DTPMOD64               = 16 # ID of module containing symbol
        R_X86_64_DTPOFF64               = 17 # Offset in TLS block
        R_X86_64_TPOFF64                = 18 # Offset in initial TLS block
        R_X86_64_TLSGD                  = 19 # PC relative offset to GD GOT block
        R_X86_64_TLSLD                  = 20 # PC relative offset to LD GOT block
        R_X86_64_DTPOFF32               = 21 # Offset in TLS block
        R_X86_64_GOTTPOFF               = 22 # PC relative offset to IE GOT entry
        R_X86_64_TPOFF32                = 23 # Offset in initial TLS block
        R_X86_64_PC64                   = 24 # PC relative 64 bit
        R_X86_64_GOTOFF64               = 25 # 64 bit offset to GOT
        R_X86_64_GOTPC32                = 26 # :nodoc:
        R_X86_64_GOT64                  = 27 # 64 bit GOT entry offset
        R_X86_64_GOTPCREL64             = 28 # :nodoc:
        R_X86_64_GOTPC64                = 29 # :nodoc:
        R_X86_64_GOTPLT64               = 30 # Obsolete. The same as GOT64
        R_X86_64_PLTOFF64               = 31 # :nodoc:
        R_X86_64_SIZE32                 = 32 # 32-bit symbol size
        R_X86_64_SIZE64                 = 33 # 64-bit symbol size
        R_X86_64_GOTPC32_TLSDESC        = 34 # :nodoc:
        R_X86_64_TLSDESC_CALL           = 35 # :nodoc:
        R_X86_64_TLSDESC                = 36 # 2x64-bit TLS descriptor
        R_X86_64_IRELATIVE              = 37 # Adjust indirectly by program base
        R_X86_64_RELATIVE64             = 38 # 64bit adjust by program base
        R_X86_64_PC32_BND               = 39 # :nodoc:
        R_X86_64_PLT32_BND              = 40 # :nodoc:
        R_X86_64_GOTPCRELX              = 41 # :nodoc:
        R_X86_64_REX_GOTPCRELX          = 42 # :nodoc:
        R_X86_64_CODE_4_GOTPCRELX       = 43 # :nodoc:
        R_X86_64_CODE_4_GOTTPOFF        = 44 # :nodoc:
        R_X86_64_CODE_4_GOTPC32_TLSDESC = 45 # :nodoc:
        R_X86_64_CODE_5_GOTPCRELX       = 46 # :nodoc:
        R_X86_64_CODE_5_GOTTPOFF        = 47 # :nodoc:
        R_X86_64_CODE_5_GOTPC32_TLSDESC = 48 # :nodoc:
        R_X86_64_CODE_6_GOTPCRELX       = 49 # :nodoc:
        R_X86_64_CODE_6_GOTTPOFF        = 50 # :nodoc:
        R_X86_64_CODE_6_GOTPC32_TLSDESC = 51 # :nodoc:
        R_X86_64_GNU_VTINHERIT          = 250 # GNU C++ hack
        R_X86_64_GNU_VTENTRY            = 251 # GNU C++ hack
      end
    end
  end
end
