# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of XGATE.
      module XGATE
        R_XGATE_NONE          = 0 # :nodoc:
        R_XGATE_8             = 1 # :nodoc:
        R_XGATE_PCREL_8       = 2 # :nodoc:
        R_XGATE_16            = 3 # :nodoc:
        R_XGATE_32            = 4 # :nodoc:
        R_XGATE_PCREL_16      = 5 # :nodoc:
        R_XGATE_GNU_VTINHERIT = 6 # :nodoc:
        R_XGATE_GNU_VTENTRY   = 7 # :nodoc:
        R_XGATE_24            = 8 # :nodoc:
        R_XGATE_LO16          = 9 # :nodoc:
        R_XGATE_GPAGE         = 10 # :nodoc:
        R_XGATE_PCREL_9       = 11 # :nodoc:
        R_XGATE_PCREL_10      = 12 # :nodoc:
        R_XGATE_IMM8_LO       = 13 # :nodoc:
        R_XGATE_IMM8_HI       = 14 # :nodoc:
        R_XGATE_IMM3          = 15 # :nodoc:
        R_XGATE_IMM4          = 16 # :nodoc:
        R_XGATE_IMM5          = 17 # :nodoc:
        R_XGATE_RL_JUMP       = 18 # :nodoc:
        R_XGATE_RL_GROUP      = 19 # :nodoc:
      end
    end
  end
end
