# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of XSTORMY16.
      module XSTORMY16
        R_XSTORMY16_NONE          = 0 # :nodoc:
        R_XSTORMY16_32            = 1 # :nodoc:
        R_XSTORMY16_16            = 2 # :nodoc:
        R_XSTORMY16_8             = 3 # :nodoc:
        R_XSTORMY16_PC32          = 4 # :nodoc:
        R_XSTORMY16_PC16          = 5 # :nodoc:
        R_XSTORMY16_PC8           = 6 # :nodoc:
        R_XSTORMY16_REL_12        = 7 # :nodoc:
        R_XSTORMY16_24            = 8 # :nodoc:
        R_XSTORMY16_FPTR16        = 9 # :nodoc:
        R_XSTORMY16_LO16          = 10 # :nodoc:
        R_XSTORMY16_HI16          = 11 # :nodoc:
        R_XSTORMY16_12            = 12 # :nodoc:
        R_XSTORMY16_GNU_VTINHERIT = 128 # :nodoc:
        R_XSTORMY16_GNU_VTENTRY   = 129 # :nodoc:
      end
    end
  end
end
