# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of XTENSA.
      module XTENSA
        R_XTENSA_NONE          = 0 # :nodoc:
        R_XTENSA_32            = 1 # :nodoc:
        R_XTENSA_RTLD          = 2 # :nodoc:
        R_XTENSA_GLOB_DAT      = 3 # :nodoc:
        R_XTENSA_JMP_SLOT      = 4 # :nodoc:
        R_XTENSA_RELATIVE      = 5 # :nodoc:
        R_XTENSA_PLT           = 6 # :nodoc:
        R_XTENSA_OP0           = 8 # :nodoc:
        R_XTENSA_OP1           = 9 # :nodoc:
        R_XTENSA_OP2           = 10 # :nodoc:
        R_XTENSA_ASM_EXPAND    = 11 # :nodoc:
        R_XTENSA_ASM_SIMPLIFY  = 12 # :nodoc:
        R_XTENSA_32_PCREL      = 14 # :nodoc:
        R_XTENSA_GNU_VTINHERIT = 15 # :nodoc:
        R_XTENSA_GNU_VTENTRY   = 16 # :nodoc:
        R_XTENSA_DIFF8         = 17 # :nodoc:
        R_XTENSA_DIFF16        = 18 # :nodoc:
        R_XTENSA_DIFF32        = 19 # :nodoc:
        R_XTENSA_SLOT0_OP      = 20 # :nodoc:
        R_XTENSA_SLOT1_OP      = 21 # :nodoc:
        R_XTENSA_SLOT2_OP      = 22 # :nodoc:
        R_XTENSA_SLOT3_OP      = 23 # :nodoc:
        R_XTENSA_SLOT4_OP      = 24 # :nodoc:
        R_XTENSA_SLOT5_OP      = 25 # :nodoc:
        R_XTENSA_SLOT6_OP      = 26 # :nodoc:
        R_XTENSA_SLOT7_OP      = 27 # :nodoc:
        R_XTENSA_SLOT8_OP      = 28 # :nodoc:
        R_XTENSA_SLOT9_OP      = 29 # :nodoc:
        R_XTENSA_SLOT10_OP     = 30 # :nodoc:
        R_XTENSA_SLOT11_OP     = 31 # :nodoc:
        R_XTENSA_SLOT12_OP     = 32 # :nodoc:
        R_XTENSA_SLOT13_OP     = 33 # :nodoc:
        R_XTENSA_SLOT14_OP     = 34 # :nodoc:
        R_XTENSA_SLOT0_ALT     = 35 # :nodoc:
        R_XTENSA_SLOT1_ALT     = 36 # :nodoc:
        R_XTENSA_SLOT2_ALT     = 37 # :nodoc:
        R_XTENSA_SLOT3_ALT     = 38 # :nodoc:
        R_XTENSA_SLOT4_ALT     = 39 # :nodoc:
        R_XTENSA_SLOT5_ALT     = 40 # :nodoc:
        R_XTENSA_SLOT6_ALT     = 41 # :nodoc:
        R_XTENSA_SLOT7_ALT     = 42 # :nodoc:
        R_XTENSA_SLOT8_ALT     = 43 # :nodoc:
        R_XTENSA_SLOT9_ALT     = 44 # :nodoc:
        R_XTENSA_SLOT10_ALT    = 45 # :nodoc:
        R_XTENSA_SLOT11_ALT    = 46 # :nodoc:
        R_XTENSA_SLOT12_ALT    = 47 # :nodoc:
        R_XTENSA_SLOT13_ALT    = 48 # :nodoc:
        R_XTENSA_SLOT14_ALT    = 49 # :nodoc:
        R_XTENSA_TLSDESC_FN    = 50 # :nodoc:
        R_XTENSA_TLSDESC_ARG   = 51 # :nodoc:
        R_XTENSA_TLS_DTPOFF    = 52 # :nodoc:
        R_XTENSA_TLS_TPOFF     = 53 # :nodoc:
        R_XTENSA_TLS_FUNC      = 54 # :nodoc:
        R_XTENSA_TLS_ARG       = 55 # :nodoc:
        R_XTENSA_TLS_CALL      = 56 # :nodoc:
        R_XTENSA_PDIFF8        = 57 # :nodoc:
        R_XTENSA_PDIFF16       = 58 # :nodoc:
        R_XTENSA_PDIFF32       = 59 # :nodoc:
        R_XTENSA_NDIFF8        = 60 # :nodoc:
        R_XTENSA_NDIFF16       = 61 # :nodoc:
        R_XTENSA_NDIFF32       = 62 # :nodoc:
      end
    end
  end
end
