# frozen_string_literal: true

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    module R
      # Relocation types of Z80.
      module Z80
        R_Z80_NONE    = 0 # :nodoc:
        R_Z80_8       = 1 # :nodoc:
        R_Z80_8_DIS   = 2 # :nodoc:
        R_Z80_8_PCREL = 3 # :nodoc:
        R_Z80_16      = 4 # :nodoc:
        R_Z80_24      = 5 # :nodoc:
        R_Z80_32      = 6 # :nodoc:
        R_Z80_BYTE0   = 7 # :nodoc:
        R_Z80_BYTE1   = 8 # :nodoc:
        R_Z80_BYTE2   = 9 # :nodoc:
        R_Z80_BYTE3   = 10 # :nodoc:
        R_Z80_WORD0   = 11 # :nodoc:
        R_Z80_WORD1   = 12 # :nodoc:
        R_Z80_16_BE   = 13 # :nodoc:
      end
    end
  end
end
