# frozen_string_literal: true

require 'elftools/constants/machine'

# This file is generated by `bundle exec rake gen:constants`, do not edit it.
# Source: https://sourceware.org/cgit/binutils-gdb/tree/include/elf

module ELFTools
  module Constants
    # Relocation types, recorded in the +r_info+ of a relocation.
    #
    # Every architecture numbers them on its own, so they are grouped by
    # architecture and only loaded once one of the groups is asked for.
    module R
      autoload :AARCH64,    'elftools/constants/relocation/aarch64'
      autoload :ALPHA,      'elftools/constants/relocation/alpha'
      autoload :AMDGPU,     'elftools/constants/relocation/amdgpu'
      autoload :ARM,        'elftools/constants/relocation/arm'
      autoload :AVR,        'elftools/constants/relocation/avr'
      autoload :BFIN,       'elftools/constants/relocation/bfin'
      autoload :BPF,        'elftools/constants/relocation/bpf'
      autoload :CR16,       'elftools/constants/relocation/cr16'
      autoload :CRIS,       'elftools/constants/relocation/cris'
      autoload :CRX,        'elftools/constants/relocation/crx'
      autoload :CSKY,       'elftools/constants/relocation/csky'
      autoload :D10V,       'elftools/constants/relocation/d10v'
      autoload :D30V,       'elftools/constants/relocation/d30v'
      autoload :DLX,        'elftools/constants/relocation/dlx'
      autoload :EPIPHANY,   'elftools/constants/relocation/epiphany'
      autoload :FR30,       'elftools/constants/relocation/fr30'
      autoload :FRV,        'elftools/constants/relocation/frv'
      autoload :FT32,       'elftools/constants/relocation/ft32'
      autoload :H8,         'elftools/constants/relocation/h8'
      autoload :HPPA,       'elftools/constants/relocation/hppa'
      autoload :I370,       'elftools/constants/relocation/i370'
      autoload :I386,       'elftools/constants/relocation/i386'
      autoload :I860,       'elftools/constants/relocation/i860'
      autoload :I960,       'elftools/constants/relocation/i960'
      autoload :IA64,       'elftools/constants/relocation/ia64'
      autoload :IP2K,       'elftools/constants/relocation/ip2k'
      autoload :IQ2000,     'elftools/constants/relocation/iq2000'
      autoload :KVX,        'elftools/constants/relocation/kvx'
      autoload :LM32,       'elftools/constants/relocation/lm32'
      autoload :LOONGARCH,  'elftools/constants/relocation/loongarch'
      autoload :M32C,       'elftools/constants/relocation/m32c'
      autoload :M32R,       'elftools/constants/relocation/m32r'
      autoload :M68HC11,    'elftools/constants/relocation/m68hc11'
      autoload :M68K,       'elftools/constants/relocation/m68k'
      autoload :MCORE,      'elftools/constants/relocation/mcore'
      autoload :MEP,        'elftools/constants/relocation/mep'
      autoload :METAG,      'elftools/constants/relocation/metag'
      autoload :MICROBLAZE, 'elftools/constants/relocation/microblaze'
      autoload :MIPS,       'elftools/constants/relocation/mips'
      autoload :MMIX,       'elftools/constants/relocation/mmix'
      autoload :MN10200,    'elftools/constants/relocation/mn10200'
      autoload :MN10300,    'elftools/constants/relocation/mn10300'
      autoload :MOXIE,      'elftools/constants/relocation/moxie'
      autoload :MSP430,     'elftools/constants/relocation/msp430'
      autoload :MSP430X,    'elftools/constants/relocation/msp430x'
      autoload :MT,         'elftools/constants/relocation/mt'
      autoload :NDS32,      'elftools/constants/relocation/nds32'
      autoload :NFP,        'elftools/constants/relocation/nfp'
      autoload :NFP3200,    'elftools/constants/relocation/nfp3200'
      autoload :NIOS2,      'elftools/constants/relocation/nios2'
      autoload :OR1K,       'elftools/constants/relocation/or1k'
      autoload :PJ,         'elftools/constants/relocation/pj'
      autoload :PPC,        'elftools/constants/relocation/ppc'
      autoload :PPC64,      'elftools/constants/relocation/ppc64'
      autoload :PRU,        'elftools/constants/relocation/pru'
      autoload :RISCV,      'elftools/constants/relocation/riscv'
      autoload :RL78,       'elftools/constants/relocation/rl78'
      autoload :RX,         'elftools/constants/relocation/rx'
      autoload :S12Z,       'elftools/constants/relocation/s12z'
      autoload :S390,       'elftools/constants/relocation/s390'
      autoload :SCORE,      'elftools/constants/relocation/score'
      autoload :SH,         'elftools/constants/relocation/sh'
      autoload :SPARC,      'elftools/constants/relocation/sparc'
      autoload :SPU,        'elftools/constants/relocation/spu'
      autoload :TIC6X,      'elftools/constants/relocation/tic6x'
      autoload :TILEGX,     'elftools/constants/relocation/tilegx'
      autoload :TILEPRO,    'elftools/constants/relocation/tilepro'
      autoload :V800,       'elftools/constants/relocation/v800'
      autoload :V850,       'elftools/constants/relocation/v850'
      autoload :VAX,        'elftools/constants/relocation/vax'
      autoload :VISIUM,     'elftools/constants/relocation/visium'
      autoload :WASM32,     'elftools/constants/relocation/wasm32'
      autoload :X86_64,     'elftools/constants/relocation/x86_64'
      autoload :XGATE,      'elftools/constants/relocation/xgate'
      autoload :XSTORMY16,  'elftools/constants/relocation/xstormy16'
      autoload :XTENSA,     'elftools/constants/relocation/xtensa'
      autoload :Z80,        'elftools/constants/relocation/z80'

      # The architecture that relocates each machine.
      # @return [Hash{Integer => Symbol}]
      MACHINES = {
        EM::EM_386 => :I386,
        EM::EM_68HC11 => :M68HC11,
        EM::EM_68HC12 => :M68HC11,
        EM::EM_68K => :M68K,
        EM::EM_860 => :I860,
        EM::EM_960 => :I960,
        EM::EM_AARCH64 => :AARCH64,
        EM::EM_ADAPTEVA_EPIPHANY => :EPIPHANY,
        EM::EM_ALPHA => :ALPHA,
        EM::EM_ALTERA_NIOS2 => :NIOS2,
        EM::EM_AMDGPU => :AMDGPU,
        EM::EM_ARM => :ARM,
        EM::EM_AVR => :AVR,
        EM::EM_BLACKFIN => :BFIN,
        EM::EM_BPF => :BPF,
        EM::EM_CR16 => :CR16,
        EM::EM_CRIS => :CRIS,
        EM::EM_CRX => :CRX,
        EM::EM_CSKY => :CSKY,
        EM::EM_CYGNUS_FRV => :FRV,
        EM::EM_CYGNUS_MEP => :MEP,
        EM::EM_D10V => :D10V,
        EM::EM_D30V => :D30V,
        EM::EM_DLX => :DLX,
        EM::EM_FR30 => :FR30,
        EM::EM_FT32 => :FT32,
        EM::EM_H8S => :H8,
        EM::EM_H8_300 => :H8,
        EM::EM_H8_300H => :H8,
        EM::EM_IAMCU => :I386,
        EM::EM_IA_64 => :IA64,
        EM::EM_IP2K => :IP2K,
        EM::EM_IQ2000 => :IQ2000,
        EM::EM_KVX => :KVX,
        EM::EM_LATTICEMICO32 => :LM32,
        EM::EM_LOONGARCH => :LOONGARCH,
        EM::EM_M32C => :M32C,
        EM::EM_M32R => :M32R,
        EM::EM_MCORE => :MCORE,
        EM::EM_METAG => :METAG,
        EM::EM_MICROBLAZE => :MICROBLAZE,
        EM::EM_MIPS => :MIPS,
        EM::EM_MMIX => :MMIX,
        EM::EM_MN10200 => :MN10200,
        EM::EM_MN10300 => :MN10300,
        EM::EM_MOXIE => :MOXIE,
        EM::EM_MSP430 => :MSP430,
        EM::EM_MT => :MT,
        EM::EM_NDS32 => :NDS32,
        EM::EM_NFP => :NFP,
        EM::EM_OR1K => :OR1K,
        EM::EM_PARISC => :HPPA,
        EM::EM_PJ => :PJ,
        EM::EM_PPC => :PPC,
        EM::EM_PPC64 => :PPC64,
        EM::EM_RISCV => :RISCV,
        EM::EM_RL78 => :RL78,
        EM::EM_RX => :RX,
        EM::EM_S12Z => :S12Z,
        EM::EM_S370 => :I370,
        EM::EM_S390 => :S390,
        EM::EM_S390_OLD => :S390,
        EM::EM_SCORE => :SCORE,
        EM::EM_SH => :SH,
        EM::EM_SPARC => :SPARC,
        EM::EM_SPARC32PLUS => :SPARC,
        EM::EM_SPARCV9 => :SPARC,
        EM::EM_SPU => :SPU,
        EM::EM_TILEGX => :TILEGX,
        EM::EM_TILEPRO => :TILEPRO,
        EM::EM_TI_C6000 => :TIC6X,
        EM::EM_TI_PRU => :PRU,
        EM::EM_V800 => :V800,
        EM::EM_V850 => :V850,
        EM::EM_VAX => :VAX,
        EM::EM_VISIUM => :VISIUM,
        EM::EM_WEBASSEMBLY => :WASM32,
        EM::EM_X86_64 => :X86_64,
        EM::EM_XGATE => :XGATE,
        EM::EM_XSTORMY16 => :XSTORMY16,
        EM::EM_XTENSA => :XTENSA,
        EM::EM_Z80 => :Z80
      }.freeze
    end
  end
end
